services:
    weaviate:
        restart: unless-stopped
        image: localhost/localhost/weaviate:1.30.3-custom
        profiles: [ weaviate, infrastructure-core, infrastructure, all ]
        healthcheck:
            test:
                # The weaviate image is Alpine based and does not have curl installed.
                # wget: -q    Turns off wget output, specifically the progress bar.
                #       -S    Shows the server response, which includes the HTTP status code.
                #       -O -  Writes the content to stdout.
                # Use the IPv4 loopback address. When 'localhost' is used, wget will try to use
                # the IPv6 ::1 address where there is no listening port.
                # grep: -q    Quiet. Exit code 0 if PATTERN is found, 1 otherwise
                - CMD-SHELL
                - >-
                  wget -qS -O - http://127.0.0.1:25080/v1/.well-known/live 2>&1 | grep -q 'HTTP/1.1 200 OK'
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 5s

        ports:
            - 25080:25080
            - 25051:25051
        networks:
            - agent-poc
        volumes:
            - weaviate-data-1:/var/lib/weaviate
        secrets:
            - weaviate_secrets

        user: root
        entrypoint: [ '/custom-docker-entrypoint.sh' ]

        command: [ '--host', '0.0.0.0', '--port', '25080', '--scheme', 'http' ]

        environment:
            # Only environment variables that are important to the Docker environment
            # will be configured here. All other environment variables are extracted
            # to .env files for easier and more isolated management.
            PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
            GRPC_PORT: 25051
        env_file:
            - weaviate.env

volumes:
    weaviate-data-1:
        driver: local
