NFS_CORE_PARAM {
    Protocols = 4;
    Enable_UDP = False;
    Bind_addr = 0.0.0.0;
    NFS_Port = 2049;
    MNT_Port = 20048;
    Enable_NLM = false;
}

NFS_KRB5 {
    Active_krb5 = false;
}

EXPORT {
    Export_Id = 100;
    Path = /exports;
    Pseudo = /exports;
    Access_Type = RW;
    Squash = No_Root_Squash;

    Protocols = 4;
    Transports = TCP;

    FSAL {
        Name = VFS;
    }

    CLIENT {
        Clients = *;
        Protocols = 4;
        Access_Type = RW;
    }
}

LOG {
    Default_Log_Level = DEBUG;
}