# FSAL_VFS is the only Ganesha module for exporting standard Linux filesystem.
# This module has a broken "Spare Read" features that failes on Docker / overlay2.
# The NFS client is forced into 4.1 protocol which does not support the failing READ_PLUS.

NFS_CORE_PARAM {
    Protocols = 4;
    Enable_UDP = False;
    Bind_addr = 0.0.0.0;
    NFS_Port = 2049;
    MNT_Port = 20048;
    Enable_NLM = false;
}

NFS_KRB5 {
    Active_krb5 = false;
}

NFSV4 {
    Grace_Period = 0;
    Domain = localdomain;
    # Allow numeric UIDs to pass through without trying to map to user@domain
    # This is critical for Docker environments!
    Allow_Numeric_Owners = true;
    Only_Numeric_Owners = true;
}

EXPORT {
    Export_Id = 100;
    Path = /exports;
    Pseudo = /exports;
    Access_Type = RW;
    Squash = No_Root_Squash;
    SecType = sys;

    Protocols = 4;
    Transports = TCP;

    FSAL {
        Name = VFS;
        Disable_Open_By_Handle = true;
        Link_Support = false;
    }

    CLIENT {
        Clients = *;
        Protocols = 4;
        Access_Type = RW;
    }
}

EXPORT {
    Export_Id = 101;
    Path = /exports/backend;
    Pseudo = /backend;
    Access_Type = RW;
    Squash = No_Root_Squash;
    SecType = sys;

    Protocols = 4;
    Transports = TCP;

    FSAL {
        Name = VFS;
        Disable_Open_By_Handle = true;
        Link_Support = false;
    }

    CLIENT {
        Clients = *;
        Protocols = 4;
        Access_Type = RW;
    }
}

EXPORT {
    Export_Id = 102;
    Path = /exports/frontend;
    Pseudo = /frontend;
    Access_Type = RW;
    Squash = No_Root_Squash;
    SecType = sys;

    Protocols = 4;
    Transports = TCP;

    FSAL {
        Name = VFS;
        Disable_Open_By_Handle = true;
        Link_Support = false;
    }

    CLIENT {
        Clients = *;
        Protocols = 4;
        Access_Type = RW;
    }
}

LOG {
    Default_Log_Level = DEBUG;
    Components {
        FSAL = FULL_DEBUG;
        NFS4 = FULL_DEBUG;
    }
}