
MDCACHE {
    # Keep the path-to-inode mapping for 15 seconds
    # (Default is often 1 second, which causes the CPU spikes you see)
    Attr_Expiration_Time = 15;

    # Increase the number of entries Ganesha can remember
    Max_Entries = 200000;
    Full_Entries_Size = 100000;
    #    Max_Entries = 16384;
    Entries_HWMark = 12288;

    # Performance tuning for the cache itself
    NParts = 31;
    Cache_FDs = true;

    # Use this to prevent the "Stale Handle" loop
    # when Unison deletes/replaces files
    Dir_Chunk = 0;
}

NFS_CORE_PARAM {
    Protocols = 4;
    Enable_UDP = False;
    Bind_addr = 0.0.0.0;
    NFS_Port = 2049;
    MNT_Port = 20048;
    Enable_NLM = false;
    # Increase interval to reduce "spinning" (value in microseconds)
    # 100000 = 100ms
    upcall_interval = 2000000;
    # Reduce the number of worker threads to prevent "thundering herd"
    # on the CPU. For a small server, 16-32 is usually plenty.
    RPC_Max_Connections = 16;
}

NFS_KRB5 {
    Active_krb5 = false;
}

NFSV4 {
    Grace_Period = 0;
    Domain = localdomain;
    # Allow numeric UIDs to pass through without trying to map to user@domain
    # This is critical for Docker environments!
    Allow_Numeric_Owners = true;
    Only_Numeric_Owners = true;
}

EXPORT {
    Export_Id = 100;
    Path = /exports;
    Pseudo = /exports;
    Access_Type = RW;
    Squash = No_Root_Squash;
    SecType = sys;

    Protocols = 4;
    Transports = TCP;

    # FSAL_VFS is the only Ganesha module for exporting standard Linux filesystem.
    # This module has a broken "Spare Read" features that failes on Docker / overlay2.
    # The NFS client is forced into 4.1 protocol which does not support the failing READ_PLUS.
    FSAL {
        Name = VFS;
        Disable_Open_By_Handle = true;
        Link_Support = false;
    }

    CLIENT {
        Clients = *;
        Protocols = 4;
        Access_Type = RW;
    }
}

EXPORT {
    Export_Id = 101;
    Path = /exports/backend;
    Pseudo = /backend;
    Access_Type = RW;
    Squash = No_Root_Squash;
    SecType = sys;

    Protocols = 4;
    Transports = TCP;

    # FSAL_VFS is the only Ganesha module for exporting standard Linux filesystem.
    # This module has a broken "Spare Read" features that failes on Docker / overlay2.
    # The NFS client is forced into 4.1 protocol which does not support the failing READ_PLUS.
    FSAL {
        Name = VFS;
        Disable_Open_By_Handle = true;
        Link_Support = false;
    }

    CLIENT {
        Clients = *;
        Protocols = 4;
        Access_Type = RW;
    }
}

EXPORT {
    Export_Id = 102;
    Path = /exports/frontend;
    Pseudo = /frontend;
    Access_Type = RW;
    Squash = No_Root_Squash;
    SecType = sys;

    Protocols = 4;
    Transports = TCP;

    # FSAL_VFS is the only Ganesha module for exporting standard Linux filesystem.
    # This module has a broken "Spare Read" features that failes on Docker / overlay2.
    # The NFS client is forced into 4.1 protocol which does not support the failing READ_PLUS.
    FSAL {
        Name = VFS;
        Disable_Open_By_Handle = true;
        Link_Support = false;
    }

    CLIENT {
        Clients = *;
        Protocols = 4;
        Access_Type = RW;
    }
}

LOG {
    # Dropping from EVENT to WARN is critical for CPU in Docker
    Default_Log_Level = WARN;
    Components {
        FSAL = WARN;
        NFS4 = WARN;
    }
}