name: clickhouse

services:
  init-clickhouse-volumes:
    restart: 'no'

    image: 'docker.io/debian:bookworm-slim'
    profiles: [ init-volumes, clickhouse, infrastructure-core,  infrastructure, all ]

    # No network is needed to initialize named volumes
    network_mode: none
    volumes:
      - clickhouse-data-1:/data-1
      - clickhouse-data-2:/data-2

    entrypoint: 'bash'
    command:
      - '-c'
      # Beware that docker-compose also performs variable interpolation.
      # So we need to escape the dollar sign with $$name so that bash
      # will recieve our embedded script with $name. 
      - |
        set -ex ;

        for VOL in 'data-1' 'data-2'
        do
          touch /$$VOL/.initialized
          ## chown -R 101:101 /$$VOL
          chmod -R 777 /$$VOL
          ls -ld /$$VOL
        done


  clickhouse:
    restart: unless-stopped
    depends_on:
      init-clickhouse-volumes:
        condition: service_completed_successfully

    image: clickhouse:24.12.3
    profiles: [ clickhouse, infrastructure-core, infrastructure, all ]

    # environment:
    #   # Only environment variables that are important to the Docker environment
    #   # will be configured here. All other environment variables are extracted
    #   # to .env files for easier and more isolated management.
    #   CLICKHOUSE_RUN_AS_ROOT: 1
    ports:
      - '28123:8123'
      - '28000:9000'
      - '28009:9009'
    networks:
      - agent-poc
    volumes:
      - clickhouse-data-1:/var/lib/clickhouse
      - clickhouse-data-2:/var/log/clickhouse-server
      - ./custom-config.xml:/etc/clickhouse-server/config.d/custom-config.xml
      - ./custom-default.xml:/etc/clickhouse-server/users.d/custom-default.xml
      - ./custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
    secrets:
      - clickhouse_env
      - clickhouse_server_crt
      - clickhouse_server_key
      - clickhouse_admin_user_xml

    entrypoint: [ '/custom-docker-entrypoint.sh' ]
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    # 
    # command: [ clickhouse ]
    # set shared memory limit when using docker-compose
    user: root
    shm_size: 128mb
    mem_limit: 8g
    memswap_limit: 16g
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

    healthcheck:
      test:
        # The clickhouse/clickhouse image does not have curl installed. And since the image is based on
        # busybox, curl is not available.
        # wget: -q    Turns off wget output, specifically the progress bar.
        #       -S    Shows the server response, which includes the HTTP status code.
        #       -O -  Writes the content to stdout.
        # Use the IPv4 loopback address. When 'localhost' is used, wget will try to use
        # the IPv6 ::1 address where there is no listening port.
        # grep: -q    Quiet. Exit code 0 if PATTERN is found, 1 otherwise
        - CMD-SHELL
        - >-
          wget -qS -O - http://localhost:8123/ping 2>&1
          | grep -q 'HTTP/1.1 200 OK'
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 5s

  clickhouse-init:

    image: localhost/localhost/debian-slim-util:1.0
    profiles: [ clickhouse, infrastructure-core, infrastructure, all ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      clickhouse_HOST: clickhouse
    env_file:
      - clickhouse-init.env
    networks:
      - agent-poc
    volumes:
      - ../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh
      - ../dependency-gate/wait_for_resource.sh:/wait_for_resource.sh
      - ./init-clickhouse.sh:/init-clickhouse.sh
    secrets:
      - clickhouse_env
      - langfuse_clickhouse_env

    entrypoint: [ '/bin/bash' ]
    command: [ /init-clickhouse.sh ]

volumes:
  clickhouse-data-1:
    driver: local
  clickhouse-data-2:
    driver: local
