name: clickhouse

services:
  init-clickhouse-volumes:
    restart: 'no'

    image: 'debian:bookworm-slim'
    profiles: [ init-volumes, clickhouse, infrastructure, all ]

    # No network is needed to initialize named volumes
    network_mode: none
    volumes:
      - clickhouse-data-1:/data-1
      - clickhouse-data-2:/data-2

    entrypoint: 'bash'
    command:
      - '-c'
      # Beware that docker-compose also performs variable interpolation.
      # So we need to escape the dollar sign with $$name so that bash
      # will recieve our embedded script with $name. 
      - |
        set -ex ;

        for VOL in 'data-1' 'data-2'
        do
          touch /$$VOL/.initialized
          ## chown -R 101:101 /$$VOL
          chmod -R 777 /$$VOL
          ls -ld /$$VOL
        done


  clickhouse:
    restart: unless-stopped
    depends_on:
      init-clickhouse-volumes:
        condition: service_completed_successfully

    image: clickhouse:24.12.3
    profiles: [ clickhouse, infrastructure, all ]

    # environment:
    #   # Only environment variables that are important to the Docker environment
    #   # will be configured here. All other environment variables are extracted
    #   # to .env files for easier and more isolated management.
    #   CLICKHOUSE_RUN_AS_ROOT: 1
    ports:
      - '28123:8123'
      - '28000:9000'
      - '28009:9009'
    networks:
      - agent-poc
    volumes:
      - clickhouse-data-1:/var/lib/clickhouse
      - clickhouse-data-2:/var/log/clickhouse-server
      - ./custom-config.xml:/etc/clickhouse-server/config.d/custom-config.xml
      - ./custom-default.xml:/etc/clickhouse-server/users.d/custom-default.xml
      - ./admin-user.xml:/etc/clickhouse-server/users.d/admin-user.xml
      - ./server.crt:/etc/clickhouse-server/server.crt
      - ./server.key:/etc/clickhouse-server/server.key

    # # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    # entrypoint: [ 'docker-entrypoint.sh' ]
    # command: [ clickhouse ]
    # set shared memory limit when using docker-compose
    user: root
    shm_size: 128mb
    mem_limit: 8g
    memswap_limit: 16g
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:8123/ping' ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 5s

  clickhouse-init:
    depends_on:
      clickhouse:
        condition: service_healthy

    image: clickhouse:24.12.3
    profiles: [ clickhouse, infrastructure, all ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      clickhouse_HOST: clickhouse
    env_file:
      - clickhouse-init.env
      - clickhouse-init.secrets.env
    # Attach clickhouse-init directly to main container's network stack
    network_mode: service:clickhouse
    volumes:
      - ./init-clickhouse.sh:/init-clickhouse.sh

    entrypoint: [ '/bin/bash' ]
    command: [ /init-clickhouse.sh ]

volumes:
  clickhouse-data-1:
    driver: local
  clickhouse-data-2:
    driver: local
