"""add prompt table

Revision ID: 12f75b868c56
Revises: efd59824ec9f
Create Date: 2025-03-29 20:24:04.246483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12f75b868c56'
down_revision: Union[str, None] = 'efd59824ec9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    """Upgrade.
    """
    schema_upgrade()
    data_upgrade()

def downgrade():
    """Downgrade.
    """
    data_downgrade()
    schema_downgrade()

def schema_upgrade():
    """Upgrade schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'DEACTIVATED', name='agentpromptstatus').create(op.get_bind())
    op.create_table('agent_prompt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'DEACTIVATED', name='agentpromptstatus', create_type=False), nullable=False),
    sa.Column('system_prompt', sa.String(length=9000), nullable=False),
    sa.Column('human_prompt', sa.String(length=9000), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_user_id', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def schema_downgrade():
    """Downgrade schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_prompt')
    sa.Enum('ACTIVE', 'DEACTIVATED', name='agentpromptstatus').drop(op.get_bind())
    # ### end Alembic commands ###

def data_upgrade():
    """Migrate data upward.
    """
    pass

def data_downgrade():
    """Migrate data downward.
    """
    pass