"""
rename vector_ids column

Revision ID: 5c6bb5056269
Revises: 8137477f7563
Create Date: 2025-05-27 01:05:31.154576

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c6bb5056269'
down_revision: Union[str, None] = '8137477f7563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    """Upgrade."""
    schema_upgrade()
    data_upgrade()


def downgrade():
    """Downgrade."""
    data_downgrade()
    schema_downgrade()


def schema_upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracked_documents', 'pg_doc_ids', new_column_name='vector_ids')
    # ### end Alembic commands ###


def schema_downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracked_documents', 'vector_ids', new_column_name='pg_doc_ids')
    # ### end Alembic commands ###


def data_upgrade():
    """Migrate existing data upward."""


def data_downgrade():
    """Migrate existing data downward."""
