"""
added prompt columns

Revision ID: 6b3f59aa577b
Revises: 8137477f7563
Create Date: 2025-05-11 01:10:11.331223

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6b3f59aa577b'
down_revision: Union[str, None] = '8137477f7563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    """Upgrade."""
    schema_upgrade()
    data_upgrade()


def downgrade():
    """Downgrade."""
    data_downgrade()
    schema_downgrade()


def schema_upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_prompt', sa.Column('include_history', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def schema_downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_prompt', 'include_history')
    # ### end Alembic commands ###


def data_upgrade():
    """Migrate existing data upward."""


def data_downgrade():
    """Migrate existing data downward."""
