"""
Add columns to prompt table.

Revision ID: 84d90b252a78
Revises: 5c6bb5056269
Create Date: 2025-05-29 21:02:07.180693
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '84d90b252a78'
down_revision: Union[str, None] = '5c6bb5056269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    """Upgrade."""
    schema_upgrade()
    data_upgrade()


def downgrade():
    """Downgrade."""
    data_downgrade()
    schema_downgrade()


def schema_upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add owner_type column as nullable first
    op.add_column(
        'agent_prompt', sa.Column('owner_type', postgresql.ENUM('SYSTEM', 'USER', name='ownertype'), nullable=True)
    )
    op.add_column('agent_prompt', sa.Column('include_history', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def schema_downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_prompt', 'include_history')
    op.drop_column('agent_prompt', 'owner_type')
    # Drop the enum type if it's no longer used
    op.execute('DROP TYPE IF EXISTS ownertype')
    # ### end Alembic commands ###


def data_upgrade():
    """Migrate existing data upward."""
    # Set default value for existing rows (assuming they should be SYSTEM type)
    op.execute("UPDATE agent_prompt SET owner_type = 'SYSTEM' WHERE owner_type IS NULL")

    # Now make the column non-nullable
    op.alter_column('agent_prompt', 'owner_type', nullable=False)


def data_downgrade():
    """Migrate existing data downward."""
    # No data migration needed for downgrade - column will be dropped
