"""Added tracking columns

Revision ID: efd59824ec9f
Revises:
Create Date: 2025-03-21 03:07:25.075060

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'efd59824ec9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    """Upgrade."""
    schema_upgrade()
    data_upgrade()


def downgrade():
    """Downgrade."""
    data_downgrade()
    schema_downgrade()


def schema_upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new columns as nullable
    op.add_column('tracked_documents', sa.Column('source_url', sa.String(length=800), nullable=True))
    op.add_column('tracked_documents', sa.Column('content_type', sa.String(length=800), nullable=True))
    op.add_column('tracked_documents', sa.Column('download_time_utc', sa.DateTime(), nullable=True))

    # Get a connection. In offline mode, the connection is simulated and heavily assumes
    # that the SQLAlchemy models and Alembic metadata are up-to-date.
    conn = op.get_bind()

    # Reflect the table
    table = sa.Table('tracked_documents', sa.MetaData(), autoload_with=conn)

    # Populate new columns
    op.execute(table.update().values(download_time_utc=table.c.file_modified_time, source_url='', content_type=''))

    # Alter new columns to be non-nullable
    op.alter_column('tracked_documents', 'source_url', nullable=False)
    op.alter_column('tracked_documents', 'content_type', nullable=False)
    op.alter_column('tracked_documents', 'download_time_utc', nullable=False)
    # ### end Alembic commands ###


def schema_downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_documents', 'download_time_utc')
    op.drop_column('tracked_documents', 'content_type')
    op.drop_column('tracked_documents', 'source_url')
    # ### end Alembic commands ###


def data_upgrade():
    """Migrate existing data upward."""
    pass


def data_downgrade():
    """Migrate existing data downward."""
    pass
