name: readiness-checker

services:
  readiness-checker:
    restart: 'no'

    image: localhost/readiness-checker:1.0
    profiles: [ langfuse, infrastructure, all ]

    env_file:
      - readiness-checker.env
      - readiness-checker.secrets.env
    networks:
      - agent-poc
    volumes:
      - ./wait_for_resource.sh:/wait_for_resource.sh

    entrypoint: [ 'bash' ]
    command: [ '/wait_for_resource.sh' ]
    mem_limit: 128m
    memswap_limit: 128m
    # set shared memory limit when using docker-compose
    shm_size: 128mb
