services:
  dev-server:
    # Image is defined in cpu-only.compose.yml or cuda.compose.yml
    profiles: [ dev-server, all ]
    privileged: true
    user: root

    environment:
      DEBUGGER_LISTEN: true
      # Mount the FUSE directory into this container
      USE_FUSE_SRC_DIR: true
      PYTHONPYCACHEPREFIX: /home/python/.pycache
    env_file:
      - automated-pytest.env
      - opentelemetry-instrument.env
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    networks:
      - agent-poc

    healthcheck:
      test: ["CMD-SHELL", "exit 0"]

    volumes:
      # Mount docker socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount entrypoint
      - ../config/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh:ro
      # Mount start script
      - ../config/start_dev.sh:/start_dev.sh:ro
      # Mount supervisord config
      - ../config/supervisord.conf:/etc/supervisord.conf:ro
    secrets:
      - answers_secrets
      - answers_api_key_autotest_secrets
      - answers_jwt_autotest_secrets
      - answers_minio_autotest_secrets
      - answers_postgres_autotest_secrets
      - checkpoints_postgres_autotest_secrets
      - redis_secrets
      - weaviate_secrets
      - codebase_seaweedfs_secrets

    entrypoint: [ 'bash', '/custom-docker-entrypoint.sh' ]
    # Command to run the dev startup script
    command: [ '/start_dev.sh' ]

networks:
  agent-poc:
    external: true
    name: agent_agent-poc
