[supervisord]
nodaemon=true
minfds=1024
minprocs=200
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:weed-mount]
command=weed mount -filer="%(ENV_SEAWEEDFS_FILER)s" -filer.path="/buckets/codebase" -dir="/mnt/fuse" -dirAutoCreate=true -umask=000 -map.uid=1000:0 -map.gid=1000:0 -replication=000 -cacheCapacityMB=1000 %(ENV_WEED_MOUNT_EXTRA_ARGS)s
autostart=true
autorestart=true
startretries=3
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:app]
command=/run_sync.sh
user=root
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
