
services:
  init-frontend-volumes:
    restart: 'no'

    image: 'docker.io/node:22-bookworm-slim'
    profiles: [ init-volumes, frontend, all ]

    # No network is needed to initialize named volumes
    network_mode: none
    volumes:
      - frontend-home-1:/home/node/home-1
      - frontend-node-modules-1:/home/node/node-modules-1
      - traefik-acme-1:/home/node/acme-1

    entrypoint: 'bash'
    command:
      - '-c'
      # Beware that docker-compose also performs variable interpolation.
      # So we need to escape the dollar sign with $$name so that bash
      # will recieve our embedded script with $name. 
      - |
        set -ex ;

        ls -ld /home/node/

        for VOL in 'home-1' 'node-modules-1'
        do
          touch /home/node/$$VOL/.initialized
          chown -R 1000:1000 /home/node/$$VOL
          chmod -R 755 /home/node/$$VOL
          ls -ld /home/node/$$VOL
        done

        for VOL in 'acme-1'
        do
          touch /home/node/$$VOL/.initialized
          chown -R 1000:1000 /home/node/$$VOL
          chmod -R 600 /home/node/$$VOL
          ls -ld /home/node/$$VOL
        done

  frontend-dependency-gate:
    restart: 'no'

    image: localhost/localhost/debian-slim-util:1.0
    profiles: [ init-volumes, frontend, all ]

    environment:
      VITE_SERVER_HOST: vite-dev-server
      FASTAPI_HOST: fastapi-dev-server
    volumes:
      - frontend-init-signal-1:/init-signal
      - ../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh
      - ./run_dependency_gate.sh:/run_dependency_gate.sh
      - ../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh
      - ../dependency-gate/wait_for_resource.sh:/wait_for_resource.sh
    networks:
      - agent-poc

    entrypoint: 'bash'
    command: [ /run_dependency_gate.sh ]



  vite-dev-server:
    depends_on:
      init-frontend-volumes:
        condition: service_completed_successfully

    image: 'localhost/localhost/answers-frontend:node-22-bookworm'
    profiles: [ frontend, all ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      CHOKIDAR_USEPOLLING: 'true'
    #   - NODE_ENV=production
    ## Do not expose 5173 ... To prevent XSS (cross site scripting) usage, we want all
    ## traffic to go thru the reserve-proxy server at 15173.
    # ports:
    #   - '5173:5173'
    networks:
      - agent-poc
    volumes:
      - ../dependency-gate/wait_for_resource.sh:/wait_for_resource.sh
      # Mount the project directory to /app in the container
      - ./app:/app
      # Mount important script into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - ./run_dev_server.sh:/run_dev_server.sh
      # Mounting a local area to use container-installed dependencies
      - frontend-home-1:/home/node
      - frontend-node-modules-1:/app/node_modules

    command: [ '/run_dev_server.sh' ]
    user: '1000:1000'

  traefik:
    image: 'docker.io/traefik:v3.4'
    profiles: [ former-frontend, former-all ]

    ports:
      - '15170:15170'
      - '15173:15173'
    networks:
      - agent-poc
    volumes:
      # To populate HOST_USER_ID dynamically, use one of these methods:
      # 1. Export before running: export HOST_USER_ID=$(id -u) && docker compose up
      # 2. Inline: HOST_USER_ID=$(id -u) docker compose up  
      - /run/user/${HOST_USER_ID:-1000}/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.dev.yml:/etc/traefik/traefik.yml  
      - ./traefik/dynamic-dev:/etc/traefik/dynamic
      - ./traefik/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
      - traefik-acme-1:/acme
    security_opt:
      - no-new-privileges:true
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

    entrypoint: ['/custom-docker-entrypoint.sh']
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    command: ['traefik']

    healthcheck:
      test:
        # The langfuse/langfuse image does not have curl installed. And since the image is based on
        # busybox, curl is not available.
        # wget: -q    Turns off wget output, specifically the progress bar.
        #       -S    Shows the server response, which includes the HTTP status code.
        #       -O -  Writes the content to stdout.
        # Use the IPv4 loopback address. When 'localhost' is used, wget will try to use
        # the IPv6 ::1 address where there is no listening port.
        # grep: -q    Quiet. Exit code 0 if PATTERN is found, 1 otherwise
        - CMD-SHELL
        - >-
          wget -qS -O - http://127.0.0.1:8082/ping 2>&1
          | grep -q 'HTTP/1.1 200 OK'

      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 15s

  proxy:
    depends_on:
      frontend-dependency-gate:
        condition: service_completed_successfully

    image: 'docker.io/nginx:1.27.3-bookworm'
    profiles: [ former-frontend, former-all ]

    ports:
      # Expose the vite server to the host machine
      - '15173:15173'
    networks:
      - agent-poc
    volumes:
      - ../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh
      - frontend-init-signal-1:/init-signal/
      - ./nginx/custom-docker-entrypoint.sh:/custom-docker-entrypoint.nginx.sh
      # Mount the Nginx configuration file.
      - ./nginx/nginx_default.conf:/etc/nginx/conf.d/default.conf

    entrypoint: ['/custom-docker-entrypoint.sh']
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    command: ['nginx', '-g', "daemon off;" ]

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:15173']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  frontend-home-1:
    driver: local
  frontend-node-modules-1:
    driver: local
  frontend-init-signal-1:
    driver: local
  traefik-acme-1:
    driver: local
