server {
    resolver 127.0.0.11 ipv6=off valid=5s;

    listen       15173;
    server_name  localhost;

    set $vite_dev_server http://vite-dev-server:5173;
    set $fastapi_dev_server http://fastapi-dev-server:8100;

    location / {
        proxy_pass $vite_dev_server;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /api/ {
        rewrite /api/(.*) /$1  break;
        proxy_pass $fastapi_dev_server;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
