services:
  langfuse-web:
    restart: unless-stopped

    image: localhost/localdomain-langfuse:3.24
    profiles: [ langfuse, infrastructure, all ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      HOSTNAME: 0.0.0.0
    env_file:
      - langfuse.env
      - langfuse.secrets.env
      - langfuse-web.env
      - langfuse-web.secrets.env
    ports:
      - '24000:3000'
    networks:
      - agent-poc
    volumes:
      - ./custom-web-entrypoint.sh:/custom-web-entrypoint.sh
    # # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    # entrypoint: [ 'dumb-init', '--', '/custom-web-entrypoint.sh' ]
    # command: [   'node', './web/server.js', '--keepAliveTimeout', '110000' ]
    # set shared memory limit when using docker-compose
    shm_size: 128mb

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/public/ready']
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 15s

  langfuse-worker:
    restart: unless-stopped
    depends_on:
      langfuse-web:
        condition: service_healthy

    image: localhost/localdomain-langfuse-worker:3.24
    profiles: [ langfuse, infrastructure, all ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      HOSTNAME: 0.0.0.0
    env_file:
      - langfuse.env
      - langfuse.secrets.env
    ports:
      - '24030:3030'
    networks:
      - agent-poc
    volumes:
      - ./custom-worker-entrypoint.sh:/custom-worker-entrypoint.sh

    # # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    # entrypoint: [ 'dumb-init', '--', '/custom-worker-entrypoint.sh' ]
    # command: ['node', 'worker/dist/index.js' ]
    # set shared memory limit when using docker-compose
    shm_size: 128mb
