services:

  langfuse-start-gate:
    restart: 'no'

    image: localhost/start-gate:1.0
    profiles: [ langfuse, infrastructure, all ]

    env_file:
      - start-gate.env
      - start-gate.secrets.env
    networks:
      - agent-poc

    mem_limit: 128m
    memswap_limit: 128m
    # set shared memory limit when using docker-compose
    shm_size: 128mb

  langfuse-web:
    restart: unless-stopped
    depends_on:
      langfuse-start-gate:
        condition: service_completed_successfully

    image: langfuse/langfuse:3.24
    profiles: [ langfuse, infrastructure, all ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      HOSTNAME: 0.0.0.0
    env_file:
      - langfuse.env
      - langfuse.secrets.env
      - langfuse-web.env
      - langfuse-web.secrets.env
    ports:
      - '23003:3000'
    networks:
      - agent-poc

    # set shared memory limit when using docker-compose
    shm_size: 128mb

    healthcheck:
      test:
        # The langfuse/langfuse image does not have curl installed. And since the image is based on
        # busybox, curl is not available.
        # wget: -q    Turns off wget output, specifically the progress bar.
        #       -S    Shows the server response, which includes the HTTP status code.
        #       -O -  Writes the content to stdout.
        # Use the IPv4 loopback address. When 'localhost' is used, wget will try to use
        # the IPv6 ::1 address where there is no listening port.
        # grep: -q    Quiet. Exit code 0 if PATTERN is found, 1 otherwise
        - CMD-SHELL
        - >-
          wget -qS -O - http://127.0.0.1:3000/api/public/ready 2>&1
          | grep -q 'HTTP/1.1 200 OK'

      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 15s

  langfuse-worker:
    restart: unless-stopped
    depends_on:
      langfuse-web:
        condition: service_healthy
      langfuse-start-gate:
        condition: service_completed_successfully

    image: langfuse/langfuse-worker:3.24
    profiles: [ langfuse, infrastructure, all ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      HOSTNAME: 0.0.0.0
    env_file:
      - langfuse.env
      - langfuse.secrets.env
    ports:
      - '24030:3030'
    networks:
      - agent-poc

    # set shared memory limit when using docker-compose
    shm_size: 128mb
