services:
  langfuse-web:
    restart: unless-stopped

    image: localhost/langfuse:3.24-plus-extras
    profiles: [ langfuse, infrastructure, all ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      HOSTNAME: 0.0.0.0
    env_file:
      - langfuse.env
      - langfuse.secrets.env
      - langfuse-web.env
      - langfuse-web.secrets.env
    ports:
      - '24000:3000'
    networks:
      - agent-poc

    # set shared memory limit when using docker-compose
    shm_size: 128mb

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/public/ready']
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 15s

  langfuse-worker:
    restart: unless-stopped
    depends_on:
      langfuse-web:
        condition: service_healthy

    image: localhost/langfuse-worker:3.24-plus-extras
    profiles: [ langfuse, infrastructure, all ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      HOSTNAME: 0.0.0.0
    env_file:
      - langfuse.env
      - langfuse.secrets.env
    ports:
      - '24030:3030'
    networks:
      - agent-poc

    # set shared memory limit when using docker-compose
    shm_size: 128mb
