version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 120

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = ["browser", "vitest"]

[[analyzers]]
name = "shell"