name: agent

include:
  - frontend/compose.yml
  - grafana/compose.yml
  - jaeger/compose.yml
  - minio/compose.yml
  - opensearch/compose.yml
  - otel-collector/compose.yml
  - nemo/compose.yml
  - postgres/compose.yml
  - presidio/compose.yml
  - prometheus/compose.yml
  - redis/compose.yml
  - traefik/compose.yml
  - weaviate/compose.yml

networks:
  agent-poc:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'true'
      com.docker.network.driver.mtu: 1500
    ipam:
      config:
        - subnet: 172.31.1.0/24
          gateway: 172.31.1.1

secrets:
  minio_secrets:
    file: ./secrets/minio.secrets.env
  postgres_secrets:
    file: ./secrets/postgres.secrets.env
  redis_secrets:
    file: ./secrets/redis.secrets.env
  weaviate_secrets:
    file: ./secrets/weaviate.secrets.env
  opensearch_secrets:
    file: ./secrets/opensearch.secrets.env

  redis_conf:
    file: ./secrets/redis.conf

  grafana_secrets:
    file: ./secrets/grafana.secrets.env

  celery_flower_dev_secrets:
    file: ./secrets/celery-flower-dev.secrets.env
  celery_flower_test_secrets:
    file: ./secrets/celery-flower-test.secrets.env

  answers_dev_secrets:
    file: ./secrets-dev.env
  answers_api_key_dev_secrets:
    file: ./secrets/answers-dev.api-key.secrets.env
  answers_jwt_dev_secrets:
    file: ./secrets/answers-dev.jwt.secrets.env
  answers_minio_dev_secrets:
    file: ./secrets/answers-dev.minio.secrets.env
  answers_postgres_dev_secrets:
    file: ./secrets/answers-dev.postgres.secrets.env
  checkpoints_postgres_dev_secrets:
    file: ./secrets/checkpoints-dev.postgres.secrets.env

  answers_test_secrets:
    file: ./secrets-test.env
  answers_api_key_test_secrets:
    file: ./secrets/answers-test.api-key.secrets.env
  answers_jwt_test_secrets:
    file: ./secrets/answers-test.jwt.secrets.env
  answers_minio_test_secrets:
    file: ./secrets/answers-test.minio.secrets.env
  answers_postgres_test_secrets:
    file: ./secrets/answers-test.postgres.secrets.env
  checkpoints_postgres_test_secrets:
    file: ./secrets/checkpoints-test.postgres.secrets.env
