name: agent

include:
  - clickhouse/compose.yml
  - frontend/compose.yml
  - grafana/compose.yml
  - langfuse/compose.yml
  - minio/compose.yml
  - nemo/compose.yml
  - postgres/compose.yml
  - presidio/compose.yml
  - prometheus/compose.yml
  - redis/compose.yml
  - weaviate/compose.yml

networks:
  agent-poc:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'true'
      com.docker.network.driver.mtu: 1500
    ipam:
      config:
        - subnet: 172.31.1.0/24
          gateway: 172.31.1.1

secrets:
  clickhouse_env:
    file: ./secrets/clickhouse.secrets.env
  minio_env:
    file: ./secrets/minio.secrets.env
  postgres_env:
    file: ./secrets/postgres.secrets.env
  redis_env:
    file: ./secrets/redis.secrets.env
  weaviate_env:
    file: ./secrets/weaviate.secrets.env

  redis_conf:
    file: ./secrets/redis.conf

  clickhouse_server_crt:
    file: ./secrets/clickhouse.server.crt
  clickhouse_server_key:
    file: ./secrets/clickhouse.server.key
  clickhouse_admin_user_xml:
    file: ./secrets/clickhouse.admin-user.xml

  grafana_env:
    file: ./secrets/grafana.secrets.env

  celery_flower_dev_env:
    file: ./secrets/celery-flower-dev.secrets.env
  celery_flower_test_env:
    file: ./secrets/celery-flower-test.secrets.env

  answers_dev_env:
    file: ./secrets-dev.env
  answers_jwt_dev_env:
    file: ./secrets/answers-dev.jwt.secrets.env
  answers_minio_dev_env:
    file: ./secrets/answers-dev.minio.secrets.env
  answers_postgres_dev_env:
    file: ./secrets/answers-dev.postgres.secrets.env
  checkpoints_postgres_dev_env:
    file: ./secrets/checkpoints-dev.postgres.secrets.env
  vectors_postgres_dev_env:
    file: ./secrets/vectors-dev.postgres.secrets.env

  answers_test_env:
    file: ./secrets-test.env
  answers_jwt_test_env:
    file: ./secrets/answers-test.jwt.secrets.env
  answers_minio_test_env:
    file: ./secrets/answers-test.minio.secrets.env
  answers_postgres_test_env:
    file: ./secrets/answers-test.postgres.secrets.env
  checkpoints_postgres_test_env:
    file: ./secrets/checkpoints-test.postgres.secrets.env
  vectors_postgres_test_env:
    file: ./secrets/vectors-test.postgres.secrets.env

  langfuse_clickhouse_env:
    file: ./secrets/langfuse.clickhouse.secrets.env
  langfuse_minio_env:
    file: ./secrets/langfuse.minio.secrets.env
  langfuse_postgres_env:
    file: ./secrets/langfuse.postgres.secrets.env

  langfuse_env:
    file: ./secrets/langfuse.secrets.env
  langfuse_web_env:
    file: ./secrets/langfuse-web.secrets.env
