services:
  init-opensearch-volumes:
    restart: 'no'

    image: 'docker.io/debian:bookworm-slim'
    profiles: [ init-volumes, opensearch, infrastructure-core, infrastructure, all ]

    # No network is needed to initialize named volumes
    network_mode: none
    volumes:
      - opensearch-data-1:/data-1

    entrypoint: 'bash'
    command:
      - '-c'
      # Beware that docker-compose also performs variable interpolation.
      # So we need to escape the dollar sign with $$name so that bash
      # will recieve our embedded script with $name. 
      - |
        set -ex ;

        for VOL in 'data-1'
        do
          touch /$$VOL/.initialized
          chown -R 1000:1000 /$$VOL
          chmod -R 777 /$$VOL
          ls -ld /$$VOL
        done


  opensearch:
    restart: unless-stopped
    # depends_on:
    #   init-opensearch-volumes: # If an init-volumes service were added
    #     condition: service_completed_successfully

    image: opensearchproject/opensearch:2.9.0
    hostname: opensearch
    profiles:
      - infrastructure-core
      - infrastructure
      - all

    ports:
      - "29200:9200" # HTTP
      - "29600:9600" # Transport
    networks:
      - agent-poc
    volumes:
      - opensearch-data-1:/usr/share/opensearch/data
      - ./custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh:ro
    secrets:
      - opensearch_secrets

    user: '1000:1000'
    entrypoint: /custom-docker-entrypoint.sh
    command: [ "opensearch" ]

    env_file:
      - ./opensearch.env
    environment:
      # For simpler dev setup, security plugin is disabled.
      # If enabled, OPENSEARCH_INITIAL_ADMIN_PASSWORD from secrets will be used by the image's entrypoint.
      DISABLE_SECURITY_PLUGIN: "true"

    healthcheck:
      test: ["CMD-SHELL", "curl -s --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s # OpenSearch can take a while to start

    ulimits: # Recommended for OpenSearch
      memlock:
        soft: 65536
        hard: 65536
      nofile:
        soft: 65536
        hard: 65536

volumes:
  opensearch-data-1:
    driver: local
