services:
    opensearch:
        restart: unless-stopped
        image: localhost/localhost/opensearch:2.17.1-custom
        hostname: opensearch
        profiles:
            - opensearch
            - infrastructure-core
            - infrastructure
            - all

        ports:
            - "29200:9200" # HTTP
            - "29600:9600" # Transport
        networks:
            - agent-net
        volumes:
            - opensearch-data-1:/usr/share/opensearch/data
        secrets:
            - opensearch_secrets

        user: root
        entrypoint: /custom-docker-entrypoint.sh
        command: [ "opensearch" ]

        env_file:
            - ./opensearch.env
        environment:
            # For simpler dev setup, security plugin is disabled.
            # If enabled, OPENSEARCH_INITIAL_ADMIN_PASSWORD from secrets will be used by the image's entrypoint.
            DISABLE_SECURITY_PLUGIN: "true"

        healthcheck:
            # Use the IPv4 loopback address. When 'localhost' is used, curl will try to use
            # the IPv6 ::1 address where there is no listening port.
            test: [ "CMD-SHELL", "curl -s --fail http://127.0.0.1:9200/_cluster/health || exit 1" ]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 60s # OpenSearch can take a while to start

        ulimits:
            # Recommended for OpenSearch
            memlock:
                soft: 65536
                hard: 65536
            nofile:
                soft: 65536
                hard: 65536

volumes:
    opensearch-data-1:
        driver: local
