services:


  celery-worker-autotest:
    depends_on:
      init-backend-autotest-volumes:
        condition: service_completed_successfully

    image: 'localhost/localhost/answers-backend-dev:python-3.12-cuda12'
    profiles: [ backend-autotest, all ]

    environment:
      DEBUGGER_LISTEN: true
      # Only environment variables that are important to a Docker environment
      # will be configured here. The reason is that changes to environment variables
      # configured here do require a restart before they take effect:
      # application-centric ones should be designed to avoiid a Docker container restart.
      #
      # The Python bytecode cache should be moved away from the bind-mount because
      # there is no need for it shared with the host.
      PYTHONPYCACHEPREFIX: '/home/python/.cache/pycache'
      ##
      ## Override YML is responsible for setting GPU_MODE to 'cuda12' or 'cpu'
      ##
    env_file:
      - automated-test.env
      - opentelemetry-instrument.env
    ports: # use if it is necessary to expose the container to the host machine
      - '28991:8989'
    networks:
      - agent-poc
    volumes:
      # Mount the project directory to /app in the container
      - .:/app
      # Mount important scripts into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - ./run_celery_worker.sh:/run_celery_worker.sh:ro
      - backend-autotest-init-signal-1:/init-signal
      - ../../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh:ro
      - ./custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh:ro
      - backend-autotest-home-2:/home/python
      - backend-autotest-venv-2:/app/.venv
      - backend-autotest-staging-2:/staging
      - backend-autotest-prometheus-2:/var/local/prometheus
    secrets:
      - answers_secrets
      - answers_api_key_autotest_secrets
      - answers_jwt_autotest_secrets
      - answers_minio_autotest_secrets
      - answers_postgres_autotest_secrets
      - checkpoints_postgres_autotest_secrets
      - redis_secrets
      - weaviate_secrets

    user: '1000:1000'
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ 'bash', '/custom-docker-entrypoint.sh' ]
    command: [ '/run_celery_worker.sh' ]
    deploy:
      resources:
        limits:
          memory: 8G # Give enough to run Tesseract and local model
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    healthcheck:
      # When this service start for the first time, there is multiple minutes while the
      # python environment is sync'ed to the requirements file then when the celery worker
      # is starting up. A health-check based on API pinging will fail during the sync and the
      # start up.
      #
      # For now, we just check if python3 can run. Later, we will  try to come up  
      ## test: ['CMD', 'curl', '-f', 'http://localhost']
      test: ['CMD', 'python3', '--version']
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 5s

  celery-flower-autotest:
    depends_on:
      init-backend-autotest-volumes:
        condition: service_completed_successfully

    image: 'localhost/localhost/answers-backend-dev:python-3.12-cpu'
    profiles: [ backend-autotest, all ]

    environment:
      # Only environment variables that are important to a Docker environment
      # will be configured here. The reason is that changes to environment variables
      # configured here do require a restart before they take effect:
      # application-centric ones should be designed to avoiid a Docker container restart.
      #
      # The Python bytecode cache should be moved away from the bind-mount because
      # there is no need for it shared with the host.
      PYTHONPYCACHEPREFIX: '/home/python/.cache/pycache'
      GPU_MODE: cpu
    env_file:
      - backend.env
    ports: # use if it is necessary to expose the container to the host machine
      - '25557:5555'
    networks:
      agent-poc: {}
    volumes:
      ### Mount the project directory to /app in the container
      - .:/app
      # Mount important scripts into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - ./run_celery_flower.sh:/run_celery_flower.sh:ro
      - backend-autotest-init-signal-1:/init-signal
      - ../../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh:ro
      - ./custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh:ro
      - backend-autotest-home-3:/home/python
      - backend-autotest-venv-3:/app/.venv
    secrets:
      - answers_secrets
      - answers_api_key_autotest_secrets
      - answers_jwt_autotest_secrets
      - answers_minio_autotest_secrets
      - answers_postgres_autotest_secrets
      - celery_flower_autotest_secrets
      - checkpoints_postgres_autotest_secrets
      - redis_secrets
      - weaviate_secrets

    user: '1000:1000'
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ 'bash', '/custom-docker-entrypoint.sh' ]
    command: [ '/run_celery_flower.sh' ]

    healthcheck:
      # When this service start for the first time, there is multiple minutes while the
      # python environment is sync'ed to the requirements file then when the celery flower node
      # is starting up. A health-check based on API pinging will fail during the sync and the
      # start up.
      #
      # For now, we just check if python3 can run. Later, we will  try to come up  
      ## test: ['CMD', 'curl', '-f', 'http://localhost']
      test: ['CMD', 'python3', '--version']
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 5s
