services:
  celery-worker:
    image: 'localhost/localhost/agent-backend:python-3.12-cuda13'

    environment:
      GPU_MODE: cuda13

    # devices:
    #   - nvidia.com/gpu=all

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
