services:
  init-backend-volumes:
    restart: 'no'

    image: 'docker.io/python:3.12.8-slim-bookworm'
    profiles: [ init-volumes, backend, all ]

    # No network is needed to initialize named volumes
    network_mode: none
    volumes:
      - backend-home-1:/home/python/home-1
      - backend-venv-1:/home/python/venv-1
      - backend-staging-1:/home/python/staging-1
      - backend-home-2:/home/python/home-2
      - backend-venv-2:/home/python/venv-2
      - backend-staging-2:/home/python/staging-2
      - backend-home-3:/home/python/home-3
      - backend-venv-3:/home/python/venv-3

    entrypoint: 'bash'
    command:
      - '-c'
      # Beware that docker-compose also performs variable interpolation.
      # So we need to escape the dollar sign with $$name so that bash
      # will recieve our embedded script with $name. 
      - |
        set -ex ;

        ls -ld /home/python/

        for VOL in \
          'home-1' 'venv-1' 'staging-1' \
          'home-2' 'venv-2' 'staging-2' \
          'home-3' 'venv-3'
        do
          touch /home/python/$$VOL/.initialized
          chown -R 1000:1000 /home/python/$$VOL
          chmod -R 755 /home/python/$$VOL
          ls -ld /home/python/$$VOL
        done

  backend-dependency-gate:
    restart: 'no'

    image: localhost/localhost/debian-slim-util:1.0
    profiles: [ backend, infrastructure, all ]

    env_file:
      - dependency-gate.env
      - backend.env
    networks:
      - agent-poc
    volumes:
      - backend-init-signal-1:/init-signal
      - ./run_dependency_gate.sh:/run_dependency_gate.sh
      - ../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh
      - ../dependency-gate/wait_for_resource.sh:/wait_for_resource.sh
    secrets:
      - answers_minio_secrets
      - answers_postgres_secrets
      - checkpoints_postgres_secrets
      - redis_secrets
      - weaviate_secrets

    mem_limit: 128m
    memswap_limit: 128m
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    entrypoint: 'bash'
    command: [ /run_dependency_gate.sh ]



  api-server:
    depends_on:
      init-backend-volumes:
        condition: service_completed_successfully

    image: 'localhost/localhost/answers-backend:python-3.12-cuda12'
    profiles: [ backend, all ]

    environment:
      DEBUGGER_LISTEN: true
      JWT_WRITE_CLAIM_MISSING_OK: true
      # Only environment variables that are important to a Docker environment
      # will be configured here. The reason is that changes to environment variables
      # configured here do require a restart before they take effect:
      # application-centric ones should be designed to avoiid a Docker container restart.
      #
      # The Python bytecode cache should be moved away from the bind-mount because
      # there is no need for it shared with the host.
      PYTHONPYCACHEPREFIX: '/home/python/.cache/pycache'
      ##
      ## Override YML is responsible for setting GPU_MODE to 'cuda12' or 'cpu'
      ##
    env_file:
      - backend.env
      - opentelemetry-instrument.env
    ports: # use if it is necessary to expose the container to the host machine
      - '8100:8100'
    networks:
      - agent-poc
    volumes:
      # Mount the project directory to /app in the container
      - .:/app
      # Mount important scripts into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - ./run_api_server.sh:/run_api_server.sh
      - backend-init-signal-1:/init-signal
      ## - ../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh
      - ./custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
      - backend-home-1:/home/python
      - backend-venv-1:/app/.venv
      - backend-staging-1:/staging
    secrets:
      - answers_secrets
      - answers_api_key_secrets
      - answers_jwt_secrets
      - answers_minio_secrets
      - answers_postgres_secrets
      - checkpoints_postgres_secrets
      - redis_secrets
      - weaviate_secrets

    user: '1000:1000'
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ 'bash', '/custom-docker-entrypoint.sh' ]
    command: [ '/run_api_server.sh' ]
    deploy:
      resources:
        limits:
          cpus: '0.5' # 50% of available CPU resources
          memory: 4G # Give enough to run local model
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    healthcheck:
      # When this service start for the first time, there is multiple minutes while the
      # python environment is sync'ed to the requirements file then when the FastAPI server
      # is starting up. A health-check based on API pinging will fail during the sync and the
      # start up.
      #
      # For now, we just check if python3 can run. Later, we will  try to come up  
      ## test: ['CMD', 'curl', '-f', 'http://localhost']
      test: ['CMD', 'python3', '--version']
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 5s


  celery-worker:
    depends_on:
      init-backend-volumes:
        condition: service_completed_successfully

    image: 'localhost/localhost/answers-backend:python-3.12-cuda12'
    profiles: [ backend, all ]

    environment:
      DEBUGGER_LISTEN: true
      # Only environment variables that are important to a Docker environment
      # will be configured here. The reason is that changes to environment variables
      # configured here do require a restart before they take effect:
      # application-centric ones should be designed to avoiid a Docker container restart.
      #
      # The Python bytecode cache should be moved away from the bind-mount because
      # there is no need for it shared with the host.
      PYTHONPYCACHEPREFIX: '/home/python/.cache/pycache'
      ##
      ## Override YML is responsible for setting GPU_MODE to 'cuda12' or 'cpu'
      ##
    env_file:
      - backend.env
      - opentelemetry-instrument.env
    ports: # use if it is necessary to expose the container to the host machine
      - '28989:8989'
    networks:
      - agent-poc
    volumes:
      # Mount the project directory to /app in the container
      - .:/app
      # Mount important scripts into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - ./run_celery_worker.sh:/run_celery_worker.sh
      - backend-init-signal-1:/init-signal
      - ./custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
      ## - ../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh
      - backend-home-2:/home/python
      - backend-venv-2:/app/.venv
      - backend-staging-2:/staging
      - backend-prometheus-2:/var/local/prometheus
    secrets:
      - answers_secrets
      - answers_jwt_secrets
      - answers_minio_secrets
      - answers_postgres_secrets
      - checkpoints_postgres_secrets
      - redis_secrets
      - weaviate_secrets

    user: '1000:1000'
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ 'bash', '/custom-docker-entrypoint.sh' ]
    command: [ '/run_celery_worker.sh' ]
    deploy:
      resources:
        limits:
          cpus: '0.1' # 10% of available CPU resources
          memory: 8G # Give enough to run Tesseract and local model
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    healthcheck:
      # When this service start for the first time, there is multiple minutes while the
      # python environment is sync'ed to the requirements file then when the celery worker
      # is starting up. A health-check based on API pinging will fail during the sync and the
      # start up.
      #
      # For now, we just check if python3 can run. Later, we will  try to come up  
      ## test: ['CMD', 'curl', '-f', 'http://localhost']
      test: ['CMD', 'python3', '--version']
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 5s

          
  celery-flower:
    depends_on:
      init-backend-volumes:
        condition: service_completed_successfully

    image: 'localhost/localhost/answers-backend:python-3.12-cpu'
    profiles: [ backend, all ]

    environment:
      # Only environment variables that are important to a Docker environment
      # will be configured here. The reason is that changes to environment variables
      # configured here do require a restart before they take effect:
      # application-centric ones should be designed to avoiid a Docker container restart.
      #
      # The Python bytecode cache should be moved away from the bind-mount because
      # there is no need for it shared with the host.
      PYTHONPYCACHEPREFIX: '/home/python/.cache/pycache'
      GPU_MODE: cpu
    env_file:
      - backend.env
    ports: # use if it is necessary to expose the container to the host machine
      - '25555:5555'
    networks:
      agent-poc: {}
    volumes:
      # Mount the project directory to /app in the container
      - .:/app
      # Mount important scripts into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - ./run_celery_flower.sh:/run_celery_flower.sh
      - backend-init-signal-1:/init-signal
      ## - ../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh
      - ./custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
      - backend-home-3:/home/python
      - backend-venv-3:/app/.venv
    secrets:
      - answers_secrets
      - answers_jwt_secrets
      - answers_minio_secrets
      - answers_postgres_secrets
      - celery_flower_secrets
      - checkpoints_postgres_secrets
      - redis_secrets
      - weaviate_secrets

    user: '1000:1000'
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ 'bash', '/custom-docker-entrypoint.sh' ]
    command: [ '/run_celery_flower.sh' ]

    healthcheck:
      # When this service start for the first time, there is multiple minutes while the
      # python environment is sync'ed to the requirements file then when the celery flower node
      # is starting up. A health-check based on API pinging will fail during the sync and the
      # start up.
      #
      # For now, we just check if python3 can run. Later, we will  try to come up  
      ## test: ['CMD', 'curl', '-f', 'http://localhost']
      test: ['CMD', 'python3', '--version']
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 5s



  celery-exporter:

    image: 'docker.io/danihodovic/celery-exporter'
    profiles: [ backend, all ]

    env_file:
      - backend.env
      - celery-exporter.env
    ports:
      - '29808:9808'
    networks:
      agent-poc: {}
    volumes:
      - backend-init-signal-1:/init-signal
      - ./custom-docker-entrypoint.exporter.sh:/custom-docker-entrypoint.exporter.sh
    secrets:
      - redis_secrets

    entrypoint: [ 'bash', '/custom-docker-entrypoint.exporter.sh' ]
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    # command: null
    deploy:
      resources:
        limits:
          cpus: '0.1' # 10% of available CPU resources

    healthcheck:
      # The danihodovic/celery-exporter image is based on python:3.13-slim-bookworm,
      # which does not have curl or wget installed.
      # To support the health check, we use a Python one-liner that uses the standard
      # library's urllib.request module. This script will attempt to connect to
      # the /health endpoint on port 9808 and exit with a status code
      # indicating success (0) or failure (1).
      test: [
        'CMD',
        'python3',
        '-c',
        "import urllib.request, sys; sys.exit(0) if urllib.request.urlopen('http://localhost:9808/health').getcode() == 200 else sys.exit(1)"
      ]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 5s
      
#
# Named volumes are not created until the dependent service
# is started.
#
volumes:
  backend-init-signal-1:
    driver: local
  backend-home-1:
    driver: local
  backend-venv-1:
    driver: local
  backend-staging-1:
    driver: local
  backend-home-2:
    driver: local
  backend-venv-2:
    driver: local
  backend-prometheus-2:
    driver: local
  backend-staging-2:
    driver: local
  backend-home-3:
    driver: local
  backend-venv-3:
    driver: local
