services:
  init-backend-test-volumes:
    restart: 'no'

    image: 'python:3.12.8-slim-bookworm'
    profiles: [ init-volumes, backend, all ]

    # No network is needed to initialize named volumes
    network_mode: none
    volumes:
      - local-backend-test-home-1:/home/python/test-home-1
      - local-backend-test-venv-1:/home/python/test-venv-1
      - local-backend-test-staging-1:/home/python/test-staging-1
      - local-backend-test-home-2:/home/python/test-home-2
      - local-backend-test-venv-2:/home/python/test-venv-2
      - local-backend-test-staging-2:/home/python/test-staging-2
      - local-backend-test-home-4:/home/python/test-home-4
      - local-backend-test-venv-4:/home/python/test-venv-4

    entrypoint: 'bash'
    command:
      - '-c'
      # Beware that docker-compose also performs variable interpolation.
      # So we need to escape the dollar sign with $$name so that bash
      # will recieve our embedded script with $name. 
      - |
        set -ex ;

        ls -ld /home/python/

        for VOL in \
          'test-home-1' 'test-venv-1' 'test-staging-1' \
          'test-home-2' 'test-venv-2' 'test-staging-2' \
          'test-venv-4' 'test-home-4'
        do
          touch /home/python/$$VOL/.initialized
          chown -R 1000:1000 /home/python/$$VOL
          chmod -R 755 /home/python/$$VOL
          ls -ld /home/python/$$VOL
        done

  backend-test-start-gate:
    restart: 'no'

    image: localhost/start-gate:1.0
    profiles: [ backend, infrastructure, all ]

    env_file:
      - start-gate.env
    networks:
      - agent-poc
    # volumes:
    #   - ../start-gate/wait_for_resource.sh:/wait_for_resource.sh
    secrets:
      - answers_minio_env
      - answers_postgres_env
      - checkpoints_postgres_env
      - vectors_postgres_env
      - redis_env

    mem_limit: 128m
    memswap_limit: 128m
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    entrypoint: 'bash'
    command:
      - '-c'
      # Beware that docker-compose also performs variable interpolation.
      # So we need to escape the dollar sign with $$name so that bash
      # will recieve our embedded script with $name. 
      - |-

        set +e
        set +x

        source /wait_for_resource.sh

        wait_for_redis "$${REDIS_URL}"
        wait_for_minio "$${MINIO_ENDPOINT_URL}"

        DATABASE_URL=postgres://answers:$${BACKEND_POSTGRES_USER_PASSWORD}@pgvector:5432/answers

        wait_for_pgvector "$$DATABASE_URL"

        DATABASE_URL=postgres://answers_vectors:$${BACKEND_VECTORS_POSTGRES_USER_PASSWORD}@pgvector:5432/vectors

        wait_for_pgvector "$$DATABASE_URL"

        DATABASE_URL=postgres://answers_checkpoints:$${BACKEND_CHECKPOINTS_POSTGRES_USER_PASSWORD}@pgvector:5432/checkpoints

        wait_for_pgvector "$$DATABASE_URL"


  fastapi-integration-server:
    depends_on:
      init-backend-test-volumes:
        condition: service_completed_successfully
      backend-test-start-gate:
        condition: service_completed_successfully

    image: 'localhost/answers-backend:python-3.12-cuda12'
    profiles: [ backend-test, all ]

    environment:
      DEBUGGER_LISTEN: true
      # Only environment variables that are important to a Docker environment
      # will be configured here. The reason is that changes to environment variables
      # configured here do require a restart before they take effect:
      # application-centric ones should be designed to avoiid a Docker container restart.
      #
      # The Python bytecode cache should be moved away from the bind-mount because
      # there is no need for it shared with the host.
      PYTHONPYCACHEPREFIX: '/home/python/.cache/pycache'
      ##
      ## Override YML is responsible for setting GPU_MODE to 'cuda12' or 'cpu'
      ##
    env_file:
      - integration-test.env
    ports: # use if it is necessary to expose the container to the host machine
      - '8102:8100'
    networks:
      - agent-poc
    volumes:
      # Mount the project directory to /app in the container
      - .:/app
      # Mount important scripts into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - ./run_fastapi_integration_server.sh:/run_fastapi_integration_server.sh
      - ./custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
      - local-backend-test-home-1:/home/python
      - local-backend-test-venv-1:/app/.venv
      - local-backend-test-staging-1:/staging
    secrets:
      - answers_test_env
      - answers_test_jwt_env
      - answers_test_minio_env
      - answers_test_postgres_env
      - checkpoints_test_postgres_env
      - vectors_test_postgres_env
      - redis_env

    user: '1000:1000'
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ 'bash', '/custom-docker-entrypoint.sh' ]
    command: [ '/run_fastapi_integration_server.sh' ]
    deploy:
      resources:
        limits:
          memory: 4G # Give enough to run local model
        # # reservations:
        # #   devices:
        # #     - driver: nvidia
        # #       count: 1
        # #       capabilities: [gpu]

    healthcheck:
      # When this service start for the first time, there is multiple minutes while the
      # python environment is sync'ed to the requirements file then when the FastAPI server
      # is starting up. A health-check based on API pinging will fail during the sync and the
      # start up.
      #
      # For now, we just check if python3 can run. Later, we will  try to come up  
      ## test: ['CMD', 'curl', '-f', 'http://localhost']
      test: ['CMD', 'python3', '--version']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s


  celery-integration-worker:
    depends_on:
      init-backend-test-volumes:
        condition: service_completed_successfully
      backend-test-start-gate:
        condition: service_completed_successfully

    image: 'localhost/answers-backend:python-3.12-cuda12'
    profiles: [ backend-test, all ]

    environment:
      DEBUGGER_LISTEN: true
      # Only environment variables that are important to a Docker environment
      # will be configured here. The reason is that changes to environment variables
      # configured here do require a restart before they take effect:
      # application-centric ones should be designed to avoiid a Docker container restart.
      #
      # The Python bytecode cache should be moved away from the bind-mount because
      # there is no need for it shared with the host.
      PYTHONPYCACHEPREFIX: '/home/python/.cache/pycache'
      ##
      ## Override YML is responsible for setting GPU_MODE to 'cuda12' or 'cpu'
      ##
    env_file:
      - integration-test.env
    ports: # use if it is necessary to expose the container to the host machine
      - '28991:8989'
    networks:
      - agent-poc
    volumes:
      # Mount the project directory to /app in the container
      - .:/app
      # Mount important scripts into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - ./run_celery_integration_worker.sh:/run_celery_integration_worker.sh
      - ./custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
      - local-backend-test-home-2:/home/python
      - local-backend-test-venv-2:/app/.venv
      - local-backend-test-staging-2:/staging
    secrets:
      - answers_test_env
      - answers_test_jwt_env
      - answers_test_minio_env
      - answers_test_postgres_env
      - checkpoints_test_postgres_env
      - vectors_test_postgres_env
      - redis_env

    user: '1000:1000'
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ 'bash', '/custom-docker-entrypoint.sh' ]
    command: [ '/run_celery_integration_worker.sh' ]
    deploy:
      resources:
        limits:
          memory: 8G # Give enough to run Tesseract and local model
        # # reservations:
        # #   devices:
        # #     - driver: nvidia
        # #       count: 1
        # #       capabilities: [gpu]

    healthcheck:
      # When this service start for the first time, there is multiple minutes while the
      # python environment is sync'ed to the requirements file then when the celery worker
      # is starting up. A health-check based on API pinging will fail during the sync and the
      # start up.
      #
      # For now, we just check if python3 can run. Later, we will  try to come up  
      ## test: ['CMD', 'curl', '-f', 'http://localhost']
      test: ['CMD', 'python3', '--version']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s


  integration-test:
    depends_on:
      init-backend-test-volumes:
        condition: service_completed_successfully
      backend-test-start-gate:
        condition: service_completed_successfully

    image: 'localhost/answers-backend:python-3.12-cpu'
    profiles: [ backend-test, all ]

    environment:
      DEBUGGER_LISTEN: true
      # Only environment variables that are important to a Docker environment
      # will be configured here. The reason is that changes to environment variables
      # configured here do require a restart before they take effect:
      # application-centric ones should be designed to avoiid a Docker container restart.
      #
      # The Python bytecode cache should be moved away from the bind-mount because
      # there is no need for it shared with the host.
      PYTHONPYCACHEPREFIX: '/home/python/.cache/pycache'
      ##
      ## Override YML is responsible for setting GPU_MODE to 'cuda12' or 'cpu'
      ##
    env_file:
      - integration-test.env
    networks:
      - agent-poc
    volumes:
      # Mount the project directory to /app in the container
      - .:/app
      # Mount important scripts into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - ./run_integration_test.sh:/run_integration_test.sh
      - ./custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
      - local-backend-test-home-4:/home/python
      - local-backend-test-venv-4:/app/.venv
    secrets:
      - answers_env
      - answers_test_jwt_env
      - answers_test_minio_env
      - answers_test_postgres_env
      - checkpoints_test_postgres_env
      - vectors_test_postgres_env
      - redis_env

    user: '1000:1000'
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ 'bash', '/custom-docker-entrypoint.sh' ]
    command: [ '/run_integration_test.sh' ]


#
# Named volumes are not created until the dependent service
# is started.
#
volumes:
  local-backend-test-home-1:
    driver: local
  local-backend-test-venv-1:
    driver: local
  local-backend-test-staging-1:
    driver: local
  local-backend-test-home-2:
    driver: local
  local-backend-test-venv-2:
    driver: local
  local-backend-test-staging-2:
    driver: local
  local-backend-test-home-4:
    driver: local
  local-backend-test-venv-4:
    driver: local
