services:
  init-backend-volumes:
    restart: 'no'

    image: 'python:3.12.8-slim-bookworm'
    profiles: [ init-volumes, backend, all ]

    # No network is needed to initialize named volumes
    network_mode: none
    volumes: []

    entrypoint: 'bash'
    command:
      - '-c'
      # Beware that docker-compose also performs variable interpolation.
      # So we need to escape the dollar sign with $$name so that bash
      # will recieve our embedded script with $name. 
      - |
        set -ex ;

        ls -ld /home/python/

        for VOL in 'home-1' 'home-2' 'home-3' 'venv-1' 'venv-2' 'venv-3' \
          'staging-1' 'staging-2'
        do
          touch /home/python/$$VOL/.initialized
          chown -R 1000:1000 /home/python/$$VOL
          chmod -R 755 /home/python/$$VOL
          ls -ld /home/python/$$VOL
        done

  fastapi-dev-server:
    depends_on:
      init-backend-volumes:
        condition: service_completed_successfully

    image: 'localhost/answers-backend:python-3.12-cuda12'
    profiles: [ backend, all ]

    environment:
      # Only environment variables that are important to a Docker environment
      # will be configured here. The reason is that changes to environment variables
      # configured here do require a restart before they take effect:
      # application-centric ones should be designed to avoiid a Docker container restart.
      #
      # The Python bytecode cache should be moved away from the bind-mount because
      # there is no need for it shared with the host.
      PYTHONPYCACHEPREFIX: '/home/python/.cache/pycache'
      ##
      ## Override YML is responsible for setting GPU_MODE to 'cuda12' or 'cpu'
      ##
    ports: # use if it is necessary to expose the container to the host machine
      - '8100:8100'
    networks:
      - agent-poc
    volumes:
      # Mount the project directory to /app in the container
      - { type: bind, source: ., target: /app }
      # Mount important scripts into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - { type: bind, source: ./run_fastapi_dev_server.sh, target: /run_fastapi_dev_server.sh }
      - { type: bind, source: ./docker/custom-docker-entrypoint.sh, target: /custom-docker-entrypoint.sh }
      ##
      ## Override YML is responsible for mounting:
      ##   target: /home/python
      ##   target: /app/.venv
      ##

    user: '1000:1000'
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ 'bash', '/custom-docker-entrypoint.sh' ]
    command: [ '/run_fastapi_dev_server.sh' ]
    deploy:
      resources:
        limits:
          memory: 4G # Give enough to run local model
        # # reservations:
        # #   devices:
        # #     - driver: nvidia
        # #       count: 1
        # #       capabilities: [gpu]

    healthcheck:
      # When this service start for the first time, there is multiple minutes while the
      # python environment is sync'ed to the requirements file then when the FastAPI server
      # is starting up. A health-check based on API pinging will fail during the sync and the
      # start up.
      #
      # For now, we just check if python3 can run. Later, we will  try to come up  
      ## test: ['CMD', 'curl', '-f', 'http://localhost']
      test: ['CMD', 'python3', '--version']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  celery-worker:
    depends_on:
      init-backend-volumes:
        condition: service_completed_successfully

    image: 'localhost/answers-backend:python-3.12-cuda12'
    profiles: [ backend, all ]

    environment:
      # Only environment variables that are important to a Docker environment
      # will be configured here. The reason is that changes to environment variables
      # configured here do require a restart before they take effect:
      # application-centric ones should be designed to avoiid a Docker container restart.
      #
      # The Python bytecode cache should be moved away from the bind-mount because
      # there is no need for it shared with the host.
      PYTHONPYCACHEPREFIX: '/home/python/.cache/pycache'
      ##
      ## Override YML is responsible for setting GPU_MODE to 'cuda12' or 'cpu'
      ##
    ports: # use if it is necessary to expose the container to the host machine
      - '8101:8101'
      - '18989:8989'
    networks:
      - agent-poc
    volumes:
      # Mount the project directory to /app in the container
      - { type: bind, source: ., target: /app }
      # Mount important scripts into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - { type: bind, source: ./run_celery_worker.sh, target: /run_celery_worker.sh }
      - { type: bind, source: ./docker/custom-docker-entrypoint.sh, target: /custom-docker-entrypoint.sh }
      ##
      ## Override YML is responsible for mounting:
      ##   target: /home/python
      ##   target: /app/.venv
      ##

    user: '1000:1000'
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ 'bash', '/custom-docker-entrypoint.sh' ]
    command: [ '/run_celery_worker.sh' ]
    deploy:
      resources:
        limits:
          memory: 8G # Give enough to run Tesseract and local model
        # # reservations:
        # #   devices:
        # #     - driver: nvidia
        # #       count: 1
        # #       capabilities: [gpu]

    healthcheck:
      # When this service start for the first time, there is multiple minutes while the
      # python environment is sync'ed to the requirements file then when the celery worker
      # is starting up. A health-check based on API pinging will fail during the sync and the
      # start up.
      #
      # For now, we just check if python3 can run. Later, we will  try to come up  
      ## test: ['CMD', 'curl', '-f', 'http://localhost']
      test: ['CMD', 'python3', '--version']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

          
  celery-flower:
    depends_on:
      init-backend-volumes:
        condition: service_completed_successfully

    image: 'localhost/answers-backend:python-3.12-cuda12'
    profiles: [ backend, all ]

    environment:
      # Only environment variables that are important to a Docker environment
      # will be configured here. The reason is that changes to environment variables
      # configured here do require a restart before they take effect:
      # application-centric ones should be designed to avoiid a Docker container restart.
      #
      # The Python bytecode cache should be moved away from the bind-mount because
      # there is no need for it shared with the host.
      PYTHONPYCACHEPREFIX: '/home/python/.cache/pycache'
      ##
      ## Override YML is responsible for setting GPU_MODE to 'cuda12' or 'cpu'
      ##
    ports: # use if it is necessary to expose the container to the host machine
      - '15555:5555'
    networks:
      - agent-poc
    volumes:
      # Mount the project directory to /app in the container
      - { type: bind, source: ., target: /app }
      # Mount important scripts into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - { type: bind, source: ./run_celery_flower.sh, target: /run_celery_flower.sh }
      - { type: bind, source: ./docker/custom-docker-entrypoint.sh, target: /custom-docker-entrypoint.sh }
      ##
      ## Override YML is responsible for mounting:
      ##   target: /home/python
      ##   target: /app/.venv
      ##

    user: '1000:1000'
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ 'bash', '/custom-docker-entrypoint.sh' ]
    command: [ '/run_celery_flower.sh' ]

    healthcheck:
      # When this service start for the first time, there is multiple minutes while the
      # python environment is sync'ed to the requirements file then when the celery flower node
      # is starting up. A health-check based on API pinging will fail during the sync and the
      # start up.
      #
      # For now, we just check if python3 can run. Later, we will  try to come up  
      ## test: ['CMD', 'curl', '-f', 'http://localhost']
      test: ['CMD', 'python3', '--version']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  celery-exporter:
    image: 'danihodovic/celery-exporter'
    profiles: [ backend, all ]

    env_file:
      - celery-exporter.env
      - celery-exporter.secrets.env
    ports:
      - '19808:9808'
    networks:
      agent-poc: {}


    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9808/health']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
      

#
# Named volumes are not created until the dependent service
# is started.
#
volumes: {}
  # local-backend-1:
  #   driver: local
  # local-backend-2:
  #   driver: local
  # local-backend-3:
  #   driver: local
