services:

  api-server-autotest:
    image: 'localhost/localhost/answers-backend:python-3.12-cpu'

    environment:
      GPU_MODE: cpu

  celery-worker-autotest:
    image: 'localhost/localhost/answers-backend:python-3.12-cpu'

    environment:
      GPU_MODE: cpu

