services:

  fastapi-server:
    image: 'localhost/localhost/answers-backend:python-3.12-cpu'

    environment:
      GPU_MODE: cpu

  dev-fastapi-server:
    image: 'localhost/localhost/answers-backend:python-3.12-cpu'

    environment:
      GPU_MODE: cpu

  celery-worker:
    image: 'localhost/localhost/answers-backend:python-3.12-cpu'

    environment:
      GPU_MODE: cpu

  dev-celery-worker:
    image: 'localhost/localhost/answers-backend:python-3.12-cpu'

    environment:
      GPU_MODE: cpu

