services:

  init-backend-volumes:
    volumes:
      - local-backend-cpuonly-home-1:/home/python/home-1
      - local-backend-cpuonly-home-2:/home/python/home-2
      - local-backend-cpuonly-home-3:/home/python/home-3
      - local-backend-cpuonly-venv-1:/home/python/venv-1
      - local-backend-cpuonly-venv-2:/home/python/venv-2
      - local-backend-cpuonly-venv-3:/home/python/venv-3
      - local-backend-cpuonly-staging-1:/home/python/staging-1
      - local-backend-cpuonly-staging-2:/home/python/staging-2


  fastapi-dev-server:
    image: 'localdomain-backend:python-3.12-cpu'

    environment:
      GPU_MODE: cpu
    volumes:
      # Mounting a local area to use container-installed dependencies
      - type: volume
        source: local-backend-cpuonly-home-1
        target: /home/python
      - type: volume
        source: local-backend-cpuonly-venv-1
        target: /app/.venv
      - type: volume
        source: local-backend-cpuonly-staging-1
        target: /staging

  celery-worker:
    image: 'localdomain-backend:python-3.12-cpu'

    environment:
      GPU_MODE: cpu
    volumes:
      # Mounting a local area to use container-installed dependencies
      - type: volume
        source: local-backend-cpuonly-home-2
        target: /home/python
      - type: volume
        source: local-backend-cpuonly-venv-2
        target: /app/.venv
      - type: volume
        source: local-backend-cpuonly-staging-2
        target: /staging

  celery-flower:
    image: 'localdomain-backend:python-3.12-cpu'

    environment:
      GPU_MODE: cpu
    volumes:
      # Mounting a local area to use container-installed dependencies
      - type: volume
        source: local-backend-cpuonly-home-3
        target: /home/python
      - type: volume
        source: local-backend-cpuonly-venv-3
        target: /app/.venv

#
# Named volumes are not created until the dependent service
# is started.
#
volumes:
  #
  # CPU only
  #
  local-backend-cpuonly-home-1:
    driver: local
  local-backend-cpuonly-venv-1:
    driver: local
  local-backend-cpuonly-staging-1:
    driver: local
  local-backend-cpuonly-home-2:
    driver: local
  local-backend-cpuonly-venv-2:
    driver: local
  local-backend-cpuonly-staging-2:
    driver: local
  local-backend-cpuonly-home-3:
    driver: local
  local-backend-cpuonly-venv-3:
    driver: local
