services:
  fastapi-dev-server:
    image: 'localhost/localhost/answers-backend:python-3.12-cuda12'

    environment:
      GPU_MODE: cuda12

    # devices:
    #   - nvidia.com/gpu=all

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  fastapi-integration-server:
    image: 'localhost/localhost/answers-backend:python-3.12-cuda12'

    environment:
      GPU_MODE: cuda12

    # devices:
    #   - nvidia.com/gpu=all

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  celery-worker:
    image: 'localhost/localhost/answers-backend:python-3.12-cuda12'

    environment:
      GPU_MODE: cuda12

    # devices:
    #   - nvidia.com/gpu=all

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  celery-integration-worker:
    image: 'localhost/localhost/answers-backend:python-3.12-cuda12'

    environment:
      GPU_MODE: cuda12

    # devices:
    #   - nvidia.com/gpu=all

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

