services:

  dev-api-server:
    image: 'localhost/localhost/answers-backend:python-3.12-cpu'

    environment:
      GPU_MODE: cpu

  dev-celery-worker:
    image: 'localhost/localhost/answers-backend:python-3.12-cpu'

    environment:
      GPU_MODE: cpu

