# Logging configuration
#
# For TOML syntax:
# see: https://toml.io/en/v1.0.0
#
# For configuration schema
# see: https://docs.python.org/3/library/logging.config.html#configuration-dictionary-schema



[loggers.log_config_watch]
level = "DEBUG"

[loggers."celery.task"]
level = "DEBUG"

[loggers."celery.worker"]
level = "DEBUG"

[loggers.sqlalchemy]
level = "WARNING"

[loggers.unstructured]
level = "DEBUG"

[loggers.pypdf]
level = "INFO"

[loggers."botocore"]
level = "INFO"

[loggers."botocore.httpchecksum"]
# Minio and Boto are skewed regarding checksum. Maybe the resolution
# is as simple as newer version. Until there is time to look, change
# logging level.
# https://github.com/minio/minio/issues/18608
level = "WARNING"
