[project]
name = "app"
version = "0.1.0"
description = "Default template for PDM package"
authors = [{ name = "", email = "" }]
dependencies = [
  "alembic>=1.15.1",
  "alembic-postgresql-enum>=1.7.0",
  "alembic-utils>=0.8.6",
  "blinker>=1.9.0",
  "celery[redis]>=5.4.0",
  "cloudpathlib[s3]>=0.20.0",
  # Implementation of the Debug Adapter Protocol for Python.
  "debugpy>=1.8.13",
  "fastapi[standard]>=0.115.6",
  "flower>=2.0.1",
  "httpx>=0.28.1",
  "icecream>=2.1.4",
  "langchain>=0.3.14",
  "langchain-anthropic>=0.3.1",
  "langchain-community>=0.3.14",
  "langchain-google-genai>=2.0.8",
  "langchain-huggingface>=0.1.2",
  "langchain-ollama>=0.2.2",
  "langchain-openai>=0.3.0",
  "langchain-postgres>=0.0.12",
  "langchain-unstructured>=0.1.6",
  "langchain-weaviate>=0.0.4",
  "langfuse>=2.58.2",
  "langgraph>=0.2.64",
  "langgraph-checkpoint-postgres>=2.0.9",
  # Explicitly specifyin min-version. See https://github.com/nltk/nltk/issues/3266
  "nltk>=3.9.1",
  # onnx is implicit dependency of unstructured
  "onnx>=1.17.0",
  # layoutparser has incorrect versions in its metadata
  "pdfplumber>=0.11.5",
  "prometheus-client>=0.21.1",
  "prometheus-fastapi-instrumentator>=7.0.2",
  "psycopg[binary,pool]>=3.2.4",
  "pydantic-settings>=2.7.0",
  "pyjwt>=2.10.1",
  "python-dotenv>=1.0.1",
  "python-magic>=0.4.27",
  "redis>=5.2.1",
  "transformers>=4.48.0",
  "unstructured[pdf]>=0.16.13",
  "watchdog[watchmedo]>=6.0.0",
]
requires-python = "==3.12.*"
readme = "README.md"
license = { text = "Apache-2.0" }

[dependency-groups]
dev = [
  "pytest>=8.3.4",
  "pytest-asyncio>=0.26.0",
  "ruff>=0.9.2",
]

[project.optional-dependencies]
cpu = [
  "torch>=2.5.1",
  "torchaudio>=2.5.1",
  "torchvision>=0.20.0"
]
cuda12 = [
  "torch>=2.5.1",
  "torchaudio>=2.5.1",
  "torchvision>=0.20.0"
]


# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"


[tool.ruff]
include = ["pyproject.toml", "src/**/*.py", "tests/**/*.py"]
line-length = 120

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = true

[tool.ruff.lint]
select = ["E", "F", "W", "C"]
ignore = [
  "D212"  # Suppress the rule that multi-line docstring summary should start at the first line
]

##[tool.ruff.rules]
##E501 = { line-length = 120 }

[tool.uv]
# Explicit declaration that the "cpu" and "cuda12" extras are in conflict
#
# See: https://github.com/astral-sh/uv/blob/main/docs/reference/settings.md#conflicts--conflicts-
#
conflicts = [
    [
      { extra = "cpu" },
      { extra = "cuda12" },
    ],
]

#
# https://docs.astral.sh/uv/reference/settings/#allow-insecure-host
#
allow-insecure-host = ["download.pytorch.org"]

# Search for every package name across all indexes, preferring the "best" version found. If a
# package version is in multiple indexes, only look at the entry for the first index.
#
# See: https://docs.astral.sh/uv/reference/settings/#index-strategy
#
index-strategy = "unsafe-best-match"

# Symbolically link packages from the wheel into the site-packages directory
#
# See: https://docs.astral.sh/uv/reference/settings/#link-mode
#
link-mode = "symlink"

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cuda12", extra = "cuda12" }
]
torchaudio = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cuda12", extra = "cuda12" }
]
torchvision = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cuda12", extra = "cuda12" }
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cuda12"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
