[pytest]
#
# Logging configuration
#
log_cli = true
log_cli_level = INFO
log_cli_format = "%(asctime)s %(levelname)s %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

#
# Asyncio configuration
# Sets the default scope for asyncio fixtures to "module" level, meaning
# async fixtures will be shared across all tests within the same module
# rather than being created/destroyed for each test function
#
asyncio_default_fixture_loop_scope = "module"

testpaths =
    tests/answers

# Additional pytest options
## addopts = --ignore=tests/doc_mgr/doc/test_ingest.py --ignore=tests/answers

# Ignore these directories when discovering tests.
norecursedirs = ["tests/doc_mgr", "tests/prompt_mgr"]
