[project]
name = "nemoguardrails-local"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "annoy>=1.17.3",
    "fastembed>=0.2.2, <=0.6.0 ; python_version >= '3.9' and python_version < '3.14'",
    "langchain-openai>=0.3.30",
    "nemoguardrails>=0.15.0",
    "opentelemetry-distro>=0.57b0",
    "opentelemetry-exporter-otlp>=1.36.0",
    "opentelemetry-exporter-zipkin-json>=1.27.0",
    "opentelemetry-instrumentation>=0.57b0",
    "opentelemetry-instrumentation-fastapi>=0.57b0",
    "opentelemetry-instrumentation-flask>=0.57b0",
    "opentelemetry-instrumentation-transformers>=0.45.4",
    "opentelemetry-sdk>=1.36.0",
]

[tool.uv]
constraint-dependencies = [
    # Fix CVE-2025-68664 https://nvd.nist.gov/vuln/detail/CVE-2025-68664
    "langchain-core>=1.0.8",
    # Fix CVE-2026-21441: https://nvd.nist.gov/vuln/detail/CVE-2026-21441
    # Fix CVE-2025-66418 https://nvd.nist.gov/vuln/detail/CVE-2025-66418
    "urllib3>=2.6.3",
    # Fix https://nvd.nist.gov/vuln/detail/CVE-2026-0994
    "protobuf>=6.33.5",
    # Fix CVE-2025-62727 https://nvd.nist.gov/vuln/detail/CVE-2025-62727
    "starlette>=0.49.1",
]
