[supervisord]
nodaemon=true
minfds=1024
minprocs=200
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:weed-mount]
command=weed mount -filer="%(ENV_SEAWEEDFS_FILER)s" -filer.path="/buckets/codebase/backend" -dir="/app/backend" -dirAutoCreate=true -umask=000 -map.uid=1000:0 -map.gid=1000:0 -cacheCapacityMB=1000 %(ENV_WEED_MOUNT_EXTRA_ARGS)s
user=root
autostart=true
autorestart=true
startretries=3
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:mount-helper]
command=/usr/local/bin/celery_mount_helper.sh
autostart=true
autorestart=false
startsecs=0
exitcodes=0
depends_on=weed-mount
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:app]
command=/custom-docker-entrypoint-nonpriv.sh /run_celery_worker.sh
user=python
# Explicitly set HOME.
environment=HOME="/home/python"
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
