api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":25170"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  
  websecure:
    address: ":25173"
    http:
      tls: {}

  web-autotest:
    address: ":25180"
    http:
      redirections:
        entryPoint:
          to: websecure-autotest
          scheme: https
  
  websecure-autotest:
    address: ":25183"
    http:
      tls: {}

  ping:
    address: ":8082"

ping:
  entryPoint: "ping"

providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

log:
  level: DEBUG

serversTransport:
  forwardingTimeouts:
    dialTimeout: "120s"
    responseHeaderTimeout: "300s"
    idleConnTimeout: "300s"
