api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":15170"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  
  websecure:
    address: ":15173"
    http:
      tls: {}

  web-autotest:
    address: ":15180"
    http:
      redirections:
        entryPoint:
          to: websecure-autotest
          scheme: https
  
  websecure-autotest:
    address: ":15183"
    http:
      tls: {}

  ping:
    address: ":8082"

ping:
  entryPoint: "ping"

providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

log:
  level: DEBUG
