services:
    # Jaeger - Distributed Tracing
    jaeger:
        image: jaegertracing/all-in-one:1.74.0
        profiles: [ jaeger, infrastructure, telemetry, all ]
        ports:
            - "26686:16686" # Jaeger UI
        command:
            - "--log-level=debug"
        environment:
            - COLLECTOR_OTLP_ENABLED=true
        healthcheck:
            # Use the IPv4 loopback address. When 'localhost' is used, wget will try to use
            # the IPv6 ::1 address where there is no listening port.
            test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:14269/" ]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 5s
        networks:
            - agent-poc
