services:

  prometheus:
    profiles: [ prometheus, infrastructure, all ]
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus-data-1:/prometheus
    ports:
      - 19090:9090
    networks:
      - agent-poc
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    depends_on:
      alertmanager:
        condition: service_started
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9090/-/healthy']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  alertmanager:
    profiles: [ prometheus, infrastructure, all ]
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 19093:9093
    networks:
      - agent-poc
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9093/-/healthy']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s


volumes:
  prometheus-data-1:
    driver: local
