global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - static_configs: 
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: fastapi-dev-server
    metrics_path: /metrics
    static_configs:
      - targets: [ 'fastapi-dev-server:8100']
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: '^(.*)'
        action: replace
        replacement: 'fastapi_${1}'

  - job_name: celery-worker
    metrics_path: /metrics
    static_configs:
      - targets: [ 'celery-worker:8989']
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: '^(.*)'
        action: replace
        replacement: 'worker_${1}'

  - job_name: celery-exporter
    metrics_path: /metrics
    static_configs:
      - targets: [ 'celery-exporter:9808']
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: '^((python_|process_).*)'
        action: replace
        replacement: 'celery_exporter_${1}'

  - job_name: celery-flower
    metrics_path: /metrics
    static_configs:
      - targets: [ 'celery-flower:5555' ]
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: '^((python_|process_).*)'
        action: replace
        replacement: 'flower_${1}'

rule_files:
  - 'alert.rules.yml'
