api:
  dashboard: true
  insecure: true

entryPoints:
  web1:
    address: ":15170"
    http:
      redirections:
        entryPoint:
          to: websecure1
          scheme: https
  
  websecure1:
    address: ":15173"
    http:
      tls: {}

  web2:
    address: ":15180"
    http:
      redirections:
        entryPoint:
          to: websecure2
          scheme: https
  
  websecure2:
    address: ":15183"
    http:
      tls: {}

  ping:
    address: ":8082"

ping:
  entryPoint: "ping"

providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

log:
  level: DEBUG
