services:
  grafana:
    restart: unless-stopped

    profiles: [ grafana, infrastructure, all ]
    image: grafana/grafana

    env_file:
      - grafana.env
      - grafana.secrets.env
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - grafana-data-1:/var/lib/grafana
    ports:
      - 13000:3000
    networks:
      - agent-poc

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s


volumes:
  grafana-data-1:
    driver: local
