name: nemo

services:
  nemo-guardrails:
    restart: unless-stopped

    image: nemo-guardrails:latest
    profiles: [ nemo, infrastructure, all ]

    env_file:
      - nemo.env
    ports:
      - '27500:8000'
    networks:
      - agent-poc
    volumes:
      - ./config:/config
      - ./custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
      # - ./docker/nemoguardrails/pyproject.toml:/nemoguardrails/pyproject.toml
      # - ./docker/nemoguardrails/poetry.lock:/nemoguardrails/poetry.lock
      # - ./docker/nemoguardrails/nemoguardrails:/app/nemoguardrails
    secrets:
      - answers_dev_secrets


    entrypoint: [ '/custom-docker-entrypoint.sh' ]
    # The option --config=/config is required for multi-config support.
    command: ["server", "--config=/config"]

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
