name: agent

include:
  - api-server/deploy/cpu-only.compose.yml
  - api-server/deploy/cpu-only-autotest.compose.yml
  - celery-worker/deploy/cpu-only.compose.yml
  - celery-worker/deploy/cpu-only-autotest.compose.yml
