name: agent

include:
  - common.compose.yml
  - api-server/deploy/cpu-only.compose.yml
  - api-server/deploy/cpu-only-autotest.compose.yml
  - celery-worker/deploy/cpu-only.compose.yml
  - webui-server/deploy/compose.yml
  - webui-server/deploy/compose-autotest.yml
