services:
    nfs:
        ## restart: unless-stopped
        restart: no

        image: localhost/localhost/nfs:latest
        profiles: [ nfs, infrastructure-core, infrastructure, all ]
        privileged: true

        ports:
            - "111:111"
            - "2049:2049"
            - "20048:20048"
        networks:
            - agent-poc
        volumes:
            - ../config/docker-entrypoint.sh:/docker-entrypoint.sh:ro
            - ../config/ganesha.conf:/etc/ganesha/ganesha.conf:ro
            - ../config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
            # Bind mount the root of this repository into the staging directory for Unison sync
            - ../../../:/staging/

        cap_add:
            - SYS_ADMIN
            - NET_BIND_SERVICE
            - SYS_RESOURCE
            - CAP_DAC_READ_SEARCH
            - CAP_DAC_OVERRIDE
            - CAP_FOWNER
            - CAP_SETUID
            - CAP_SETGID

        entrypoint: [ '/docker-entrypoint.sh' ]
        # The option --config=/config is required for multi-config support.
        command: [ "ganesha.nfsd", "-F", "-L", "/dev/stdout" ]
