name: readiness-checker

services:
  test-custom:
    restart: 'no'

    image: 'python:3.12.8-slim-bookworm'

    # No network is needed to initialize named volumes
    network_mode: none
    volumes: []

    entrypoint: 'bash'
    command:
      - '-c'
      # Beware that docker-compose also performs variable interpolation.
      # So we need to escape the dollar sign with $$name so that bash
      # will recieve our embedded script with $name. 
      - |
        set -ex ;

        ls -a /run/secrets

        export $( grep -o -v "^#" /run/secrets/* | xargs -n1 )

        env | sort


    secrets:
      - redis
      - postgres


secrets:
   redis:
     file: ./secrets/redis.secrets.env
   postgres:
     file: ./secrets/postgres.secrets.env

