http:
  routers:
    vite-app:
      rule: "Host(`localhost`)"
      entryPoints:
        - websecure
      service: vite-service
      tls: {}

    fastapi:
      rule: "Host(`localhost`) && PathPrefix(`/api/`)"
      entryPoints:
        - websecure
      service: fastapi-service
      middlewares:
        - strip-api-prefix
      tls: {}

  middlewares:
    strip-api-prefix:
      stripPrefix:
        prefixes:
          - "/api"

  services:
    vite-service:
      loadBalancer:
        servers:
          - url: "http://vite-integration-server:5173"

    fastapi-service:
      loadBalancer:
        servers:
          - url: "http://fastapi-integration-server:8100"
