services:
  dev-tools:
    # Image is defined in cpu-only.compose.yml or cuda.compose.yml
    profiles: [ dev-tools, all ]
    privileged: true
    user: root

    environment:
      DEBUGGER_LISTEN: true
      USE_CODEBASE_SYNC: false
      USE_BOOTSTRAP_INSTALL: true
      ENABLE_SSHD: false
      ENABLE_MUTAGEN_SYNC: false
      RUN_AS_UID: ${DEV_UID:-1000}
      RUN_AS_GID: ${DEV_GID:-1000}
      PYTHONPYCACHEPREFIX: /home/python/.pycache
    env_file:
      - automated-pytest.env
      - opentelemetry-instrument.env
    networks:
      - agent-net

    volumes:
      # Mount docker socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount host codebase
      - ../../:/app
      # Mount entrypoint
      - ../config/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh:ro
      # Mount non-privileged entrypoint
      - ../config/custom-docker-entrypoint-nonpriv.sh:/custom-docker-entrypoint-nonpriv.sh:ro
      # Mount supervisord config
      - ../config/supervisord.conf:/etc/supervisord.conf:ro

    entrypoint: [ 'bash', '/custom-docker-entrypoint.sh' ]

networks:
  agent-net:
    external: true
    name: agent_agent-net
