services:
  dev-tools:
    image: 'localhost/localhost/answers-dev-tools:python-3.12-cuda12'

    environment:
      GPU_MODE: cuda12

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
