"""Added tracking columns

Revision ID: efd59824ec9f
Revises: 
Create Date: 2025-03-21 03:07:25.075060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd59824ec9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_documents', sa.Column('source_url', sa.String(length=800), nullable=True))
    op.add_column('tracked_documents', sa.Column('content_type', sa.String(length=800), nullable=True))
    op.add_column('tracked_documents', sa.Column('download_time_utc', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_documents', 'download_time_utc')
    op.drop_column('tracked_documents', 'content_type')
    op.drop_column('tracked_documents', 'source_url')
    # ### end Alembic commands ###
