name: redis

services:
    redis:
        restart: unless-stopped
        image: localhost/localhost/redis:7.4.1-custom
        profiles: [ redis, infrastructure-core, infrastructure, all ]

        ports:
            - '26379:6379'
        networks:
            - agent-net
        volumes:
            - redis-data-1:/data
            - ../config/redis.conf.template:/redis.conf.template:ro
        secrets:
            - redis_secrets

        user: root
        entrypoint: [ '/custom-docker-entrypoint.sh' ]
        # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
        # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
        command: [ 'redis-server', 'redis.conf' ]
        mem_limit: 1g
        memswap_limit: 2g

        healthcheck:
            test: [ 'CMD', 'redis-cli', 'ping' ]
            interval: 30s
            timeout: 10s
            retries: 10
            start_period: 5s

volumes:
    redis-data-1:
        driver: local
