services:
  api-server:
    image: 'localhost/localhost/answers-backend:python-3.12-cuda12'
    profiles: [  api-server, backend, all ]

    environment:
      DEBUGGER_LISTEN: true
      JWT_WRITE_CLAIM_MISSING_OK: true
      # Only environment variables that are important to a Docker environment
      # will be configured here. The reason is that changes to environment variables
      # configured here do require a restart before they take effect:
      # application-centric ones should be designed to avoiid a Docker container restart.
      #
      ##
      ## Override YML is responsible for setting GPU_MODE to 'cuda12' or 'cpu'
      ##
    env_file:
      - backend.env
      - opentelemetry-instrument.env
    ports: # use if it is necessary to expose the container to the host machine
      - '8100:8100'
    networks:
      - agent-poc
    volumes:
      # Mount the project directory to /app in the container
      ### - ../../../backend:/app
      # Mount important scripts into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - ../config/run_api_server.sh:/run_api_server.sh:ro
      - backend-init-signal-1:/init-signal
      ##SRC - ../../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh
      - ../config/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh:ro
      - backend-staging-1:/staging
    secrets:
      - answers_secrets
      - answers_api_key_secrets
      - answers_jwt_secrets
      - answers_seaweedfs_secrets
      - answers_postgres_secrets
      - checkpoints_postgres_secrets
      - redis_secrets
      - weaviate_secrets

    user: root
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ '/custom-docker-entrypoint.sh' ]
    command: [ '/run_api_server.sh' ]
    deploy:
      resources:
        limits:
          cpus: '0.5' # 50% of available CPU resources
          memory: 4G # Give enough to run local model
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    healthcheck:
      # When this service starts for the first time, it may take several minutes to sync
      # the python environment and start the FastAPI server. A healthcheck based on
      # API pinging would fail during this period.
      #
      # For now, we verify that python3 is executable.
      # Note: If switching to an API-based check, use http://127.0.0.1 to avoid
      # IPv6 resolution issues with 'localhost'.
      ## test: ['CMD', 'curl', '-f', 'http://127.0.0.1']
      test: ['CMD', 'python3', '--version']
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 5s


  python-build:
    image: 'localhost/localhost/answers-backend-dev:python-3.12-cpu'
    profiles: [
      python-build
    ]

    environment:
      # Only environment variables that are important to a Docker environment
      # will be configured here. The reason is that changes to environment variables
      # configured here do require a restart before they take effect:
      # application-centric ones should be designed to avoiid a Docker container restart.


      ##
      ## Override YML is responsible for setting GPU_MODE to 'cuda12' or 'cpu'
      ##
      GPU_MODE: cpu
      # Mount the FUSE directory into this container
      USE_FUSE_SRC_DIR: false
      #
      PYTHONPYCACHEPREFIX: /home/python/.pycache
      # Codebase bucket credentials
      CODEBASE_ACCESS_KEY:
    env_file:
      - backend.env
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    networks:
      agent-poc: {}
    volumes:
      # Mount important scripts into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - ../config/run_build_backend.sh:/run_build_backend.sh:ro
      # Mount dist directory
      - ../../dist:/dist
      # Mount source directory
      - ../../../backend:/app/backend
      ## - ../../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh
      - ../config/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
      - ../config/custom-docker-entrypoint-nonpriv.sh:/custom-docker-entrypoint-nonpriv.sh:ro

    user: root
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ '/custom-docker-entrypoint.sh' ]
    command: [ '/run_build_backend.sh' ]



#
# Named volumes are not created until the dependent service
# is started.
#
volumes:
  backend-init-signal-1:
    driver: local
  backend-staging-1:
    driver: local
