services:
  backend-autotest-dependency-gate:
    restart: 'no'

    image: localhost/localhost/debian-slim-util:1.0
    profiles: [ backend-autotest, infrastructure, all ]

    env_file:
      - automated-test.env
    networks:
      - agent-poc
    volumes:
      - backend-autotest-init-signal-1:/init-signal
      - ../config/run_dev_dependency_gate.sh:/run_dev_dependency_gate.sh:ro
      - ../../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh:ro
      - ../../dependency-gate/wait_for_resource.sh:/wait_for_resource.sh:ro
    secrets:
      - answers_postgres_autotest_secrets
      - answers_seaweedfs_autotest_secrets
      - checkpoints_postgres_autotest_secrets
      - redis_secrets
      - weaviate_secrets

    mem_limit: 128m
    memswap_limit: 128m
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    entrypoint: 'bash'
    command: [ /run_dev_dependency_gate.sh ]


  api-server-autotest:
    image: 'localhost/localhost/answers-backend-dev:python-3.12-cuda12'
    profiles: [ backend-autotest, all ]
    privileged: true

    environment:
      DEBUGGER_LISTEN: true
      JWT_WRITE_CLAIM_MISSING_OK: true
      # Only environment variables that are important to a Docker environment
      # will be configured here. The reason is that changes to environment variables
      # configured here do require a restart before they take effect:
      # application-centric ones should be designed to avoiid a Docker container restart.


      ##
      ## Override YML is responsible for setting GPU_MODE to 'cuda12' or 'cpu'
      ##
      ##
      USE_CODEBASE_SYNC: true
      USE_BOOTSTRAP_INSTALL: true
      TELEMETRY_EDITABLE_INSTALL: true
      ENABLE_SSHD: true
      PYTHONPYCACHEPREFIX: /home/python/.pycache
    env_file:
      - automated-test.env
      - opentelemetry-instrument.env
    networks:
      - agent-poc
    volumes:
      # Mount important scripts into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - ../config/run_api_server.sh:/run_api_server.sh:ro
      - backend-autotest-init-signal-1:/init-signal
      ##SRC - ../../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh:ro
      - ../config/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh:ro
      - ../config/supervisord.conf:/etc/supervisord.conf:ro
      - ../config/custom-docker-entrypoint-nonpriv.sh:/custom-docker-entrypoint-nonpriv.sh:ro
    secrets:
      - answers_secrets
      - answers_api_key_autotest_secrets
      - answers_jwt_autotest_secrets
      - answers_seaweedfs_autotest_secrets
      - answers_postgres_autotest_secrets
      - checkpoints_postgres_autotest_secrets
      - redis_secrets
      - weaviate_secrets
      - mutagen_sshd_authorized_keys

    user: root
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ 'bash', '/custom-docker-entrypoint.sh' ]
    command: [ '/run_api_server.sh' ]
    deploy:
      resources:
        limits:
          memory: 4G # Give enough to run local model
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    healthcheck:
      # When this service start for the first time, there is multiple minutes while the
      # python environment is sync'ed to the requirements file then when the FastAPI server
      # is starting up. A health-check based on API pinging will fail during the sync and the
      # start up.
      #
      # For now, we just check if python3 can run. Later, we will  try to come up  
      ## test: ['CMD', 'curl', '-f', 'http://localhost']
      test: ['CMD', 'python3', '--version']
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 5s



  automated-pytest:
    image: 'localhost/localhost/answers-backend-dev:python-3.12-cpu'
    profiles: [ backend-autotest, automated-pytest, all ]
    privileged: true

    environment:
      DEBUGGER_LISTEN: true
      # Only environment variables that are important to a Docker environment
      # will be configured here. The reason is that changes to environment variables
      # configured here do require a restart before they take effect:
      # application-centric ones should be designed to avoiid a Docker container restart.



      # https://github.com/docker/compose/issues/6029
      PYTHONUNBUFFERED: 1
      ##
      ## Override YML is responsible for setting GPU_MODE to 'cuda12' or 'cpu'
      ##
      GPU_MODE: cpu
      ##
      ## Override YML is responsible for setting GPU_MODE to 'cuda12' or 'cpu'
      ##
      ##
      USE_CODEBASE_SYNC: true
      USE_BOOTSTRAP_INSTALL: true
      TELEMETRY_EDITABLE_INSTALL: true
      ENABLE_SSHD: true
      PYTHONPYCACHEPREFIX: /home/python/.pycache
      APP_AUTORESTART: 'false'
    env_file:
      - automated-test.env
      - opentelemetry-instrument.env
    networks:
      - agent-poc
    volumes:
      - backend-autotest-init-signal-1:/init-signal
      # Mount important scripts into the container when we are
      # avoiding rebuilding images to capture their latest version.
      - ../config/run_automated_test.sh:/run_automated_test.sh:ro
      ##SRC - ../../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh:ro
      - ../config/mount_helper.sh:/usr/local/bin/mount_helper.sh:ro
      - ../config/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh:ro
      - ../config/custom-docker-entrypoint-nonpriv.sh:/custom-docker-entrypoint-nonpriv.sh:ro
      - ../config/supervisord.conf:/etc/supervisord.conf:ro
      - ../config/stop_supervisor.sh:/stop_supervisor.sh:ro
      ##SRC - backend-autotest-home-4:/home/python
      ##SRC - backend-autotest-venv-4:/app/backend/.venv
    secrets:
      - answers_secrets
      - answers_api_key_autotest_secrets
      - answers_jwt_autotest_secrets
      - answers_seaweedfs_autotest_secrets
      - answers_postgres_autotest_secrets
      - celery_flower_autotest_secrets
      - checkpoints_postgres_autotest_secrets
      - redis_secrets
      - weaviate_secrets
      - mutagen_sshd_authorized_keys

    user: root
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ 'bash', '/custom-docker-entrypoint.sh' ]
    command: [ '/run_automated_test.sh' ]


#
# Named volumes are not created until the dependent service
# is started.
#
volumes:
  backend-autotest-init-signal-1:
    driver: local

networks:
  agent-poc:
    name: agent_agent-poc
    external: true
