[project]
name = "core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jun Masui", email = "76625904+junmasui@users.noreply.github.com" }
]
requires-python = "==3.12.*"
dependencies = [
  "core-db",
  "core-public",
  "blinker>=1.9.0",
  "cloudpathlib[s3]>=0.20.0",
  "httpx>=0.28.1",
  "langchain>=1.2.7",
  "langchain-anthropic>=1.3.1",
  "langchain-community>=0.4.1",
  "langchain-google-genai>=4.2.0",
  "langchain-huggingface>=1.2.0",
  "langchain-ollama>=1.0.1",
  "langchain-openai>=1.1.7",
  "langchain-postgres>=0.0.16",
  "langchain-unstructured>=1.0.1",
  "langchain-weaviate>=0.0.6",
  "langgraph>=1.0.7",
  "langgraph-checkpoint-postgres>=2.0.9",
  # Explicitly specifyin min-version. See https://github.com/nltk/nltk/issues/3266
  "msgpack>=1.1.1",
  "nest_asyncio>=1.6.0",
  "nltk>=3.9.1",
  # layoutparser has incorrect versions in its metadata
  "pdfplumber>=0.11.5",
  "psycopg[binary,pool]>=3.2.4",
  "pydantic-settings>=2.7.0",
  "python-magic>=0.4.27",
  "redis>=5.2.1",
  "scikit-learn>=1.6.1",
  "sentence-transformers>=3.4.1",
  "transformers>=4.56.1",
  "unstructured[all-docs,docx,pdf]>=0.16.13",
  "weaviate-client>=4.15.4",
]

[project.optional-dependencies]
cpu = [
  "torch==2.10.0",
]
cuda13 = [
  "torch==2.10.0",
]


[tool.uv]
# Explicit declaration that the "cpu" and "cuda13" extras are in conflict
#
# See: https://github.com/astral-sh/uv/blob/main/docs/reference/settings.md#conflicts--conflicts-
#
conflicts = [
    [
      { extra = "cpu" },
      { extra = "cuda13" },
    ],
]

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"
