name: slim-util

services:
    slim-util:
        image: localhost/localhost/debian-slim-util:1.0
        profiles: [ run-and-done ]
        networks:
            - agent-net
        stdin_open: true
        tty: true
        entrypoint: [ /bin/bash ]

networks:
    agent-net:
        external: true
