name: minio

services:
  minio:
    restart: unless-stopped

    image: docker.io/minio/minio:RELEASE.2025-05-24T17-08-30Z-cpuv1
    profiles: [ minio, infrastructure-core, infrastructure, all ]

    env_file:
      - minio.env
    ports:
      - '29000:9000'
      - '29001:9001'
    networks:
      - agent-poc
    volumes:
      - minio-data-2:/data
      - ./custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
    secrets:
      - minio_secrets

    entrypoint: [ '/custom-docker-entrypoint.sh' ]
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    command: server /data --console-address ':9001'
    mem_limit: 512m
    memswap_limit: 1g

    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  minio-init-dependency-gate:
    restart: 'no'

    image: localhost/localhost/debian-slim-util:1.0
    profiles: [ minio, infrastructure-core, infrastructure, all, run-and-done ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      MINIO_ENDPOINT_URL: http://minio:9000
    env_file:
      - minio.env
    networks:
      - agent-poc
    volumes:
      - minio-init-signal-1:/init-signal
      - ./run_dependency_gate.sh:/run_dependency_gate.sh
      - ../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh
      - ../dependency-gate/wait_for_resource.sh:/wait_for_resource.sh
    secrets:
      - postgres_secrets

    mem_limit: 128m
    memswap_limit: 128m
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    entrypoint: 'bash'
    command: [ /run_dependency_gate.sh ]


  minio-init:
    restart: 'no'

    image: docker.io/minio/minio:RELEASE.2025-05-24T17-08-30Z-cpuv1
    profiles: [ minio, infrastructure-core, infrastructure, all, run-and-done ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      MINIO_ENDPOINT_URL: http://minio:9000
    env_file:
      - minio-init.env
    networks:
      - agent-poc
    volumes:
      - minio-init-signal-1:/init-signal
      - ./init-minio.sh:/init-minio.sh
    secrets:
      - minio_secrets
      - answers_minio_secrets

    entrypoint: [ /bin/sh ]
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    command: /init-minio.sh

  minio-test-init:
    restart: 'no'

    image: docker.io/minio/minio:RELEASE.2025-05-24T17-08-30Z-cpuv1
    profiles: [ minio, infrastructure-core, infrastructure, all, run-and-done ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      MINIO_ENDPOINT_URL: http://minio:9000
    env_file:
      - minio-test-init.env
    networks:
      - agent-poc
    volumes:
      - minio-init-signal-1:/init-signal
      - ./init-minio.sh:/init-minio.sh
    secrets:
      - minio_secrets
      - answers_minio_dev_secrets

    entrypoint: [ /bin/sh ]
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    command: /init-minio.sh

volumes:
  minio-data-2:
    driver: local
  minio-init-signal-1:
    driver: local
