name: minio

services:
  minio:
    restart: unless-stopped

    image: localdomain-minio:2024-12-13T22-19-12Z
    profiles: [ minio, infrastructure, all ]

    env_file:
      - minio.env
      - minio.secrets.env
    ports:
      - '29000:9000'
      - '29001:9001'
    networks:
      - agent-poc
    volumes:
      - type: volume
        source: minio-data-2
        target: /data

    command: server /data --console-address ':9001'
    mem_limit: 512m
    memswap_limit: 1g

    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  minio-init:
    restart: 'no'
    depends_on:
      minio:
        condition: service_healthy

    image: localdomain-minio:2024-12-13T22-19-12Z
    profiles: [ minio, infrastructure, all ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      MINIO_ENDPOINT_URL: http://minio:9000
    env_file:
      - minio-init.env
      - minio-init.secrets.env
    # Attach minio-init directly to main container's network stack
    network_mode: service:minio
    volumes:
      - ./init-minio.sh:/init-minio.sh

    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ /bin/sh ]
    command: /init-minio.sh

volumes:
  minio-data-2:
    driver: local
