name: postgres

services:
  postgres:
    restart: unless-stopped

    image: postgres:17.5-bookworm
    profiles: [ postgres, infrastructure-core, infrastructure, all ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - postgres.env
    ports:
      - '25432:5432'
    networks:
      - agent-poc
    volumes:
      - postgres-data-1:/var/lib/postgresql/data
      - ./custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
    secrets:
      - postgres_secrets

    entrypoint: [ '/custom-docker-entrypoint.sh' ]
    # When entrypoint is specified in the compose file, the CMD in the Dockerfile is
    # will be ignored. Hence, extract its value and add it here in the compose file:
    #   docker inspect postgres:17.5-bookworm | jq '.[0].Config.Cmd'
    command: [ postgres ]
    mem_limit: 512m
    memswap_limit: 1g
    # set shared memory limit when using docker-compose
    shm_size: 128mb

    healthcheck:
      # POSTGRES_USER is defined inside postgres.env
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 5s


  postgres-init-dependency-gate:
    restart: 'no'

    image: localhost/localhost/debian-slim-util:1.0
    profiles: [ postgres, infrastructure-core, infrastructure, all, run-and-done ]

    env_file:
      - postgres.env
    networks:
      - agent-poc
    volumes:
      - postgres-init-signal-1:/init-signal
      - ./run_dependency_gate.sh:/run_dependency_gate.sh
      - ../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh
      - ../dependency-gate/wait_for_resource.sh:/wait_for_resource.sh
    secrets:
      - postgres_secrets

    mem_limit: 128m
    memswap_limit: 128m
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    entrypoint: 'bash'
    command: [ /run_dependency_gate.sh ]



  postgres-init:

    image: localhost/localhost/debian-slim-util:1.0
    #image: localhost/localhost/postgres:17.2-with-postgres
    profiles: [ postgres, infrastructure-core, infrastructure, all, run-and-done ]

    env_file:
      - postgres-init.env
    networks:
      - agent-poc
    volumes:
      - postgres-init-signal-1:/init-signal
      - ../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh
      - ./init-db.sql.template:/init-db.sql.template
      - ./init-postgres.sh:/init-postgres.sh
    secrets:
      - postgres_secrets
      - answers_postgres_secrets
      - checkpoints_postgres_secrets

    entrypoint: [ '/bin/bash' ]
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    command: [ /init-postgres.sh ]


  postgres-test-init:

    image: localhost/localhost/debian-slim-util:1.0
    # image: localhost/localhost/postgres:17.2-with-postgres
    profiles: [ postgres, infrastructure-core, infrastructure, all, run-and-done ]

    env_file:
      - postgres-test-init.env
    networks:
      - agent-poc
    volumes:
      - postgres-init-signal-1:/init-signal
      - ../dependency-gate/wait_for_gate.sh:/wait_for_gate.sh
      - ./init-db.sql.template:/init-db.sql.template
      - ./init-postgres.sh:/init-postgres.sh
    secrets:
      - postgres_secrets
      - answers_postgres_dev_secrets
      - checkpoints_postgres_dev_secrets

    entrypoint: [ '/bin/bash' ]
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    command: [ /init-postgres.sh ]

volumes:
  postgres-data-1:
    driver: local
  postgres-init-signal-1:
    driver: local
