name: pgvector

services:
  pgvector:
    restart: unless-stopped

    image: localdomain-postgres:17.2-pgvector
    profiles: [ postgres, infrastructure, all ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - pgvector.env
      - pgvector.secrets.env
    ports:
      - '25432:5432'
    networks:
      - agent-poc
    volumes:
      - pgvector-data-1:/var/lib/postgresql/data

    entrypoint: [ 'docker-entrypoint.sh' ]
    command: [ postgres ]
    mem_limit: 512m
    memswap_limit: 1g
    # set shared memory limit when using docker-compose
    shm_size: 128mb

    healthcheck:
      # POSTGRES_USER is defined inside pgvector.env
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 5s

  pgvector-init:
    depends_on:
      pgvector:
        condition: service_healthy

    image: localdomain-postgres:17.2-pgvector
    profiles: [ postgres, infrastructure, all ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      POSTGRES_HOST: pgvector
    env_file:
      - pgvector-init.env
      - pgvector-init.secrets.env
    # Attach postgres-init directly to main container's network stack
    network_mode: service:pgvector

    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    entrypoint: [ '/bin/sh' ]
    command: [ /init-postgres.sh ]

volumes:
  pgvector-data-1:
    driver: local
