name: pgvector

services:
  pgvector:
    restart: unless-stopped

    image: localhost/postgres:17.2-with-pgvector
    profiles: [ postgres, infrastructure-core, infrastructure, all ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - pgvector.env
    ports:
      - '25432:5432'
    networks:
      - agent-poc
    volumes:
      - pgvector-data-1:/var/lib/postgresql/data
      - ./custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
    secrets:
      - postgres_env

    entrypoint: [ '/custom-docker-entrypoint.sh' ]
    # When entrypoint is specified in the compose file, the CMD in the Dockerfile is
    # will be ignored. Hence, extract its value and add it here in the compose file:
    #   docker inspect localhost/postgres:17.2-with-pgvector | jq '.[0].Config.Cmd'
    command: [ postgres ]
    mem_limit: 512m
    memswap_limit: 1g
    # set shared memory limit when using docker-compose
    shm_size: 128mb

    healthcheck:
      # POSTGRES_USER is defined inside pgvector.env
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 5s

  pgvector-init:
    depends_on:
      pgvector:
        condition: service_healthy

    image: localhost/postgres:17.2-with-pgvector
    profiles: [ postgres, infrastructure-core, infrastructure, all ]

    environment:
      # Only environment variables that are important to the Docker environment
      # will be configured here. All other environment variables are extracted
      # to .env files for easier and more isolated management.
      POSTGRES_HOST: pgvector
    env_file:
      - pgvector-init.env
    # Attach postgres-init directly to main container's network stack
    network_mode: service:pgvector
    volumes:
      - ./init-db.sql.template:/init-db.sql.template
      - ./init-langfuse-db.sql.template:/init-langfuse-db.sql.template
      - ./init-postgres.sh:/init-postgres.sh
    secrets:
      - postgres_env
      - answers_postgres_env
      - answers_test_postgres_env
      - checkpoints_postgres_env
      - checkpoints_test_postgres_env
      - vectors_postgres_env
      - vectors_test_postgres_env
      - langfuse_postgres_env

    entrypoint: [ '/bin/sh' ]
    # Beware: when entrypoint is used in the compose file, the CMD in the Dockerfile is ignored.
    # See: https://docs.docker.com/reference/compose-file/services/#entrypoint
    command: [ /init-postgres.sh ]

volumes:
  pgvector-data-1:
    driver: local
