models:
  - type: main
    engine: openai
    model: gpt-4.1-nano


rails:
  input:
    flows:
      # - check jailbreak
      # - check toxicity
      - self check input

tracing:
  enabled: true
  adapters:
    - name: OpenTelemetry
      service_name: "nemo_guardrails"
