name: redis

services:
  redis:
    image: redis:latest
    profiles: [ redis, infrastructure, all, all-cpu ]
    ports:
      - '6379:6379'
    volumes:
      - redis-data-1:/data
    networks:
      - agent-poc
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 5s

volumes:
  redis-data-1:
    driver: local
